//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/6/2020 2:55:41 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LosIntegration.Entity.Models
{
    /// <summary>
    /// There are no comments for ExternalOriginatorConfiguration in the schema.
    /// </summary>
    public partial class ExternalOriginatorConfiguration : IEntityTypeConfiguration<ExternalOriginator>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<ExternalOriginator> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<ExternalOriginator> builder)
        {
            builder.ToTable(@"ExternalOriginator", @"dbo");
            builder.Property<short>(x => x.Id).HasColumnName(@"Id").HasColumnType(@"smallint").IsRequired().ValueGeneratedNever();
            builder.Property<string>(x => x.Name).HasColumnName(@"Name").HasColumnType(@"varchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            builder.HasKey(@"Id");
            builder.HasMany(x => x.Mappings).WithOne(op => op.ExternalOriginator).IsRequired(true).HasForeignKey(@"ExtOriginatorId");

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<ExternalOriginator> builder);

        #endregion
    }

}
