using System;
using System.Collections.Generic;
using System.Text;

namespace ByteWebConnector.Model.Models.ServiceResponseModels.ByteApi
{
	public class StatusResponse
	{
		public int StatusID { get; set; }
		public int FileDataID { get; set; }
		public short LoanStatus { get; set; }
		public DateTime? LeadDate { get; set; }
		public DateTime? ApplicationDate { get; set; }
		public short FollowUpFlag { get; set; }
		public DateTime? PrequalDate { get; set; }
		public DateTime? CreditOnlyDate { get; set; }
		public DateTime? InProcessingDate { get; set; }
		public DateTime? SubmittedDate { get; set; }
		public DateTime? ApprovedDate { get; set; }
		public DateTime? ResubmittedDate { get; set; }
		public DateTime? DeclinedDate { get; set; }
		public DateTime? InClosingDate { get; set; }
		public DateTime? ClosedDate { get; set; }
		public DateTime? CanceledDate { get; set; }
		public DateTime? SchedClosingDate { get; set; }
		public DateTime? SchedApprovalDate { get; set; }
		public DateTime? SigningDate { get; set; }
		public short GFEDeliveryMethod { get; set; }
		public DateTime? GFEDeliveryDate { get; set; }
		public DateTime? GFERevisionDate { get; set; }
		public DateTime? FundingDate { get; set; }
		public DateTime? PurchaseContractDate { get; set; }
		public bool ExcludeFromManagementReports { get; set; }
		public DateTime? FollowUpDate { get; set; }
		public DateTime? CreditFirstIssuedDate { get; set; }
		public DateTime? SuspendedDate { get; set; }
		public DateTime? DocsSignedDate { get; set; }
		public DateTime? SchedFundingDate { get; set; }
		public DateTime? CustomStatus1Date { get; set; }
		public DateTime? CustomStatus2Date { get; set; }
		public DateTime? CustomStatus3Date { get; set; }
		public DateTime? CustomStatus4Date { get; set; }
		public DateTime? CustomStatus5Date { get; set; }
		public DateTime? CustomStatus6Date { get; set; }
		public DateTime? OtherDate1 { get; set; }
		public DateTime? OtherDate2 { get; set; }
		public DateTime? OtherDate3 { get; set; }
		public string Notes { get; set; }
		public DateTime? LoanPurchasedDate { get; set; }
		public int GFERevisionMethod { get; set; }
		public bool DisclosureWaitingPeriodWaived { get; set; }
		public bool RedisclosureWaitingPeriodWaived { get; set; }
		public DateTime? TILRevisionDate { get; set; }
		public int TILRevisionMethod { get; set; }
		public DateTime? RecissionDate { get; set; }
		public DateTime? InvestorDueDate { get; set; }
		public DateTime? ShipByDate { get; set; }
		public DateTime? ClearToCloseDate { get; set; }
		public DateTime? ShippedDate { get; set; }
		public DateTime? CollateralSentDate { get; set; }
		public DateTime? DocsSentDate { get; set; }
		public DateTime? NoteDate { get; set; }
		public DateTime? NMLSActionDate { get; set; }
		public DateTime? StatusDate { get; set; }
		public int PredProtectResult { get; set; }
		public int ComplianceEaseRiskIndicator { get; set; }
		public DateTime? ComplianceCheckRunDate { get; set; }
		public bool ComplianceCheckOverride { get; set; }
		public DateTime? CustomStatus7Date { get; set; }
		public DateTime? CustomStatus8Date { get; set; }
		public DateTime? CustomStatus9Date { get; set; }
		public DateTime? CustomStatus10Date { get; set; }
		public DateTime? CustomStatus11Date { get; set; }
		public DateTime? AppraisalCompleted { get; set; }
		public DateTime? AppraisalDelivered { get; set; }
		public int AppraisalDeliveryMethod { get; set; }
		public DateTime? Appraisal2Completed { get; set; }
		public DateTime? Appraisal2Delivered { get; set; }
		public int Appraisal2DeliveryMethod { get; set; }
		public DateTime? AppraisalReceivedByBorrower { get; set; }
		public DateTime? Appraisal2ReceivedByBorrower { get; set; }
		public DateTime? AppraisalTimingWaiverDate { get; set; }
		public DateTime? DocsBackDate { get; set; }
		public DateTime? DocsImagedDate { get; set; }
		public DateTime? InvestorPackagedDate { get; set; }
		public DateTime? InvestorShippedDate { get; set; }
		public DateTime? InvestorSuspendedDate { get; set; }
		public DateTime? InvestorClearedDate { get; set; }
		public DateTime? InsurancePackagedDate { get; set; }
		public DateTime? InsuranceShippedDate { get; set; }
		public DateTime? InsuranceRejectedDate { get; set; }
		public DateTime? InsuranceResubmittedDate { get; set; }
		public DateTime? InsuranceObtainedDate { get; set; }
		public DateTime? InsuranceRHSRequestMailedDate { get; set; }
		public DateTime? InsuranceRHSResponseDate { get; set; }
		public DateTime? InsuranceFeeDeliveredDate { get; set; }
		public DateTime? InsuranceMIC_LGCToInvestorDate { get; set; }
		public DateTime? ServicingFirstPaymentDate { get; set; }
		public DateTime? ServicingDataSentDate { get; set; }
		public DateTime? ServicingPackageSentDate { get; set; }
		public DateTime? ServicingAuditDate { get; set; }
		public string ServicingAuditUserName { get; set; }
		public DateTime? CorrPurchaseByDate { get; set; }
		public DateTime? CorrOriginalNoteReceivedDate { get; set; }
		public DateTime? InsuringReceivedDate { get; set; }
		public DateTime? InsuranceReviewReqDate { get; set; }
		public DateTime? MortRecChangeDate { get; set; }
		public DateTime? CaseTransferReqDate { get; set; }
		public DateTime? CaseTransferCompDate { get; set; }
		public string InsuringNotes { get; set; }
		public DateTime? ShippingReceivedDate { get; set; }
		public DateTime? CollateralPackSentDate { get; set; }
		public DateTime? FinalHUDToInvestorDate { get; set; }
		public DateTime? NoteShipmentReqDate { get; set; }
		public DateTime? NoteBackToWarehouseDate { get; set; }
		public string ShippingNotes { get; set; }
		public DateTime? PMICertificateActivationDate { get; set; }
		public DateTime? PreapprovalApplicationDate { get; set; }
		public DateTime? NMLSApplicationDate { get; set; }
		public bool CDWaitingPeriodWaived { get; set; }
		public DateTime? IntentToProceedDate { get; set; }
		public DateTime? ClosingCostsExpirationDate { get; set; }
		public string ClosingCostsExpirationTimeOfDayOV { get; set; }
		public int CDDateIssuedOption { get; set; }
		public DateTime? CDDateIssuedOtherDate { get; set; }
		public bool HasSixAppDataPoints { get; set; }
		public int ApplicationTestResult { get; set; }
		public int FeeReconciliationTestResult { get; set; }
		public int TRIDDisclosureTestResult { get; set; }
		public int LEDisclosureTestResult { get; set; }
		public int CDDisclosureTestResult { get; set; }
		public int ClosingCostsExpirationTimeZoneCityOV { get; set; }
		public DateTime? CustomStatus12Date { get; set; }
		public DateTime? CustomStatus13Date { get; set; }
		public DateTime? CustomStatus14Date { get; set; }
		public DateTime? CustomStatus15Date { get; set; }
		public DateTime? CustomStatus16Date { get; set; }
		public DateTime? CustomStatus17Date { get; set; }
		public DateTime? CustomStatus18Date { get; set; }
		public DateTime? CustomStatus19Date { get; set; }
		public DateTime? CustomStatus20Date { get; set; }
		public DateTime? CustomStatus21Date { get; set; }
		public DateTime? CustomStatus22Date { get; set; }
		public DateTime? CustomStatus23Date { get; set; }
		public DateTime? CustomStatus24Date { get; set; }
		public DateTime? CustomStatus25Date { get; set; }
		public DateTime? CustomStatus26Date { get; set; }
		public DateTime? CustomStatus27Date { get; set; }
		public DateTime? CustomStatus28Date { get; set; }
		public DateTime? CustomStatus29Date { get; set; }
		public DateTime? CustomStatus30Date { get; set; }
		public bool SigningAppointmentConfirmed { get; set; }
		public int SigningAppointmentLocationType { get; set; }
		public string SigningAppointmentTime { get; set; }
		public DateTime? SigningAppointmentDate { get; set; }
		public DateTime? LastStatusChangeDateTime { get; set; }
		public int ESignTestResult { get; set; }
		public DateTime? MERSRegistrationDate { get; set; }
		public DateTime? MERSTransferDate { get; set; }
		public string MERSCurrentInvestorOrgID { get; set; }
		public string MERSCurrentServicerOrgID { get; set; }
		public string MERSCurrentSubservicerOrgID { get; set; }
		public int? InterimIntAdditionalConsentedDays { get; set; }
		public int NMLSApplicationDateCalcOption { get; set; }
	}

}
