// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Data.Mapping
{
    using LoanApplicationDb.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // AssetTypeGiftSourceBinder
    
    public partial class AssetTypeGiftSourceBinderMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<AssetTypeGiftSourceBinder>
    {
        public void Configure(EntityTypeBuilder<AssetTypeGiftSourceBinder> builder)
        {
            builder.ToTable("AssetTypeGiftSourceBinder", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.AssetTypeId).HasColumnName(@"AssetTypeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.GiftSourceId).HasColumnName(@"GiftSourceId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();

            // Foreign keys
            builder.HasOne(a => a.AssetType).WithMany(b => b.AssetTypeGiftSourceBinders).HasForeignKey(c => c.AssetTypeId).OnDelete(DeleteBehavior.SetNull); // FK_AssetTypeGiftSourceBinder_AssetType_Id
            builder.HasOne(a => a.GiftSource).WithMany(b => b.AssetTypeGiftSourceBinders).HasForeignKey(c => c.GiftSourceId).OnDelete(DeleteBehavior.SetNull); // FK_AssetTypeGiftSourceBinder_GiftSource_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
