// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Data.Mapping
{
    using LoanApplicationDb.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // BorrowerConsent
    
    public partial class BorrowerConsentMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<BorrowerConsent>
    {
        public void Configure(EntityTypeBuilder<BorrowerConsent> builder)
        {
            builder.ToTable("BorrowerConsent", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.ConsentTypeId).HasColumnName(@"ConsentTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BorrowerId).HasColumnName(@"BorrowerId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LoanApplicationId).HasColumnName(@"LoanApplicationId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ConsentText).HasColumnName(@"ConsentText").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(150);
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(300);
            builder.Property(x => x.MiddleName).HasColumnName(@"MiddleName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(300);
            builder.Property(x => x.CreatedOnUtc).HasColumnName(@"CreatedOnUtc").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsAccepted).HasColumnName(@"IsAccepted").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IpAddress).HasColumnName(@"IpAddress").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Borrower).WithMany(b => b.BorrowerConsents).HasForeignKey(c => c.BorrowerId).OnDelete(DeleteBehavior.SetNull); // FK_BorrowerConsent_Borrower
            builder.HasOne(a => a.ConsentType).WithMany(b => b.BorrowerConsents).HasForeignKey(c => c.ConsentTypeId).OnDelete(DeleteBehavior.SetNull); // FK_BorrowerConsent_ConsentType
            builder.HasOne(a => a.LoanApplication).WithMany(b => b.BorrowerConsents).HasForeignKey(c => c.LoanApplicationId).OnDelete(DeleteBehavior.SetNull); // FK_BorrowerConsent_LoanApplication
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
