// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Data.Mapping
{
    using LoanApplicationDb.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // InActiveSetupItemsSectionWise
    
    public partial class InActiveSetupItemsSectionWiseMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<InActiveSetupItemsSectionWise>
    {
        public void Configure(EntityTypeBuilder<InActiveSetupItemsSectionWise> builder)
        {
            builder.ToTable("InActiveSetupItemsSectionWise", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.EntityName).HasColumnName(@"EntityName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.EntityRefId).HasColumnName(@"EntityRefId").HasColumnType("int").IsRequired();
            builder.Property(x => x.SectionId).HasColumnName(@"SectionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.InActiveSetupItemSection).WithMany(b => b.InActiveSetupItemsSectionWises).HasForeignKey(c => c.SectionId).OnDelete(DeleteBehavior.SetNull); // FK_InActiveSetupItemsSectionWise_InActiveSetupItemSection_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
