// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Data.Mapping
{
    using LoanApplicationDb.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // _RmOtherIncomeTypeMapping
    
    public partial class RmOtherIncomeTypeMappingMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<RmOtherIncomeTypeMapping>
    {
        public void Configure(EntityTypeBuilder<RmOtherIncomeTypeMapping> builder)
        {
            builder.ToTable("_RmOtherIncomeTypeMapping", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.RmOtherIncomeTypeId).HasColumnName(@"RmOtherIncomeTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ColabaOtherIncomeTypeId).HasColumnName(@"ColabaOtherIncomeTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(100);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
