// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Milestone.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // MilestoneStatusConfiguration
    
    public partial class MilestoneStatusConfiguration : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int TenantId { get; set; } // TenantId
        public int? FromStatus { get; set; } // FromStatus
        public int? ToStatus { get; set; } // ToStatus
        public short? NoofDays { get; set; } // NoofDays
        public System.DateTime? RecurringTime { get; set; } // RecurringTime
        public bool? IsActive { get; set; } // IsActive
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child MilestoneEmailConfigurations where [MilestoneEmailConfiguration].[StatusUpdateId] point to this entity (FK_MilestoneEmailConfiguration_MilestoneStatusConfiguration)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MilestoneEmailConfiguration> MilestoneEmailConfigurations { get; set; } // MilestoneEmailConfiguration.FK_MilestoneEmailConfiguration_MilestoneStatusConfiguration

        // Foreign keys

        /// <summary>
        /// Parent Milestone pointed by [MilestoneStatusConfiguration].([FromStatus]) (FK_MilestoneStatusUpdate_MilestoneStatusUpdate)
        /// </summary>
        public virtual Milestone Milestone { get; set; } // FK_MilestoneStatusUpdate_MilestoneStatusUpdate

        public MilestoneStatusConfiguration()
        {
            MilestoneEmailConfigurations = new System.Collections.Generic.HashSet<MilestoneEmailConfiguration>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
