// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Milestone.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // Milestone
    
    public partial class Milestone : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? Order { get; set; } // Order
        public string Icon { get; set; } // Icon (length: 50)
        public string BorrowerName { get; set; } // BorrowerName (length: 50)
        public string McuName { get; set; } // McuName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public int? MilestoneTypeId { get; set; } // MilestoneTypeId

        // Reverse navigation

        /// <summary>
        /// Child MilestoneMappings where [MilestoneMapping].[MilestoneId] point to this entity (FK_MilestoneMapping_Milestone_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MilestoneMapping> MilestoneMappings { get; set; } // MilestoneMapping.FK_MilestoneMapping_Milestone_Id
        /// <summary>
        /// Parent (One-to-One) Milestone pointed by [TenantMilestone].[Id] (FK_TenantMilestone_Milestone_Id)
        /// </summary>
        public virtual TenantMilestone TenantMilestone { get; set; } // TenantMilestone.FK_TenantMilestone_Milestone_Id

        // Foreign keys

        /// <summary>
        /// Parent MilestoneType pointed by [Milestone].([MilestoneTypeId]) (FK_Milestone_MilestoneType_Id)
        /// </summary>
        public virtual MilestoneType MilestoneType { get; set; } // FK_Milestone_MilestoneType_Id

        public Milestone()
        {
            MilestoneMappings = new System.Collections.Generic.HashSet<MilestoneMapping>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
