// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // EmpDepartmentBinder
    
    public partial class EmpDepartmentBinderMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<EmpDepartmentBinder>
    {
        public void Configure(EntityTypeBuilder<EmpDepartmentBinder> builder)
        {
            builder.ToTable("EmpDepartmentBinder", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired();
            builder.Property(x => x.DepartmentId).HasColumnName(@"DepartmentId").HasColumnType("int").IsRequired();
            builder.Property(x => x.PositionId).HasColumnName(@"PositionId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Department).WithMany(b => b.EmpDepartmentBinders).HasForeignKey(c => c.DepartmentId).OnDelete(DeleteBehavior.SetNull); // FK_EmpDepartmentBinder_Department
            builder.HasOne(a => a.Employee).WithMany(b => b.EmpDepartmentBinders).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.SetNull); // FK_EmpDepartmentBinder_Employee
            builder.HasOne(a => a.Position).WithMany(b => b.EmpDepartmentBinders).HasForeignKey(c => c.PositionId).OnDelete(DeleteBehavior.SetNull); // FK_EmpDepartmentBinder_Position
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
