// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // LoanRequestProduct
    
    public partial class LoanRequestProductMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<LoanRequestProduct>
    {
        public void Configure(EntityTypeBuilder<LoanRequestProduct> builder)
        {
            builder.ToTable("LoanRequestProduct", "dbo");
            builder.HasKey(x => new { x.LoanRequestId, x.ProductId });

            builder.Property(x => x.LoanRequestId).HasColumnName(@"LoanRequestId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.LoanRequest).WithMany(b => b.LoanRequestProducts).HasForeignKey(c => c.LoanRequestId).OnDelete(DeleteBehavior.SetNull); // FK_LoanRequestProduct_LoanRequest
            builder.HasOne(a => a.Product).WithMany(b => b.LoanRequestProducts).HasForeignKey(c => c.ProductId).OnDelete(DeleteBehavior.SetNull); // FK_LoanRequestProduct_Product
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
