// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // SessionLogDetail
    
    public partial class SessionLogDetailMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<SessionLogDetail>
    {
        public void Configure(EntityTypeBuilder<SessionLogDetail> builder)
        {
            builder.ToTable("SessionLogDetail", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.RequestOnUtc).HasColumnName(@"RequestOnUtc").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UrlReferrer).HasColumnName(@"UrlReferrer").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Url).HasColumnName(@"Url").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.VisitorId).HasColumnName(@"VisitorId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.SessionLogId).HasColumnName(@"SessionLogId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Remarks).HasColumnName(@"Remarks").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.EntityTypeId).HasColumnName(@"EntityTypeId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.SessionLog).WithMany(b => b.SessionLogDetails).HasForeignKey(c => c.SessionLogId).OnDelete(DeleteBehavior.SetNull); // FK_SessionLogDetail_SessionLog
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
