// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // AdsSourceMessage

    public partial class AdsSourceMessage : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? AdSourceId { get; set; } // AdSourceId
        public int? LocalStringResourceId { get; set; } // LocalStringResourceId
        public string ResourceName { get; set; } // ResourceName (length: 256)
        public int? MessageLocationId { get; set; } // MessageLocationId

        // Foreign keys

        /// <summary>
        /// Parent AdsSource pointed by [AdsSourceMessage].([AdSourceId]) (FK_AdsSourceMessage_AdsSource)
        /// </summary>
        public virtual AdsSource AdsSource { get; set; } // FK_AdsSourceMessage_AdsSource

        /// <summary>
        /// Parent LocaleStringResource pointed by [AdsSourceMessage].([LocalStringResourceId]) (FK_AdsSourceMessage_LocaleStringResource)
        /// </summary>
        public virtual LocaleStringResource LocaleStringResource { get; set; } // FK_AdsSourceMessage_LocaleStringResource

        public AdsSourceMessage()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
