// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // BorrowerConsentLog

    public partial class BorrowerConsentLog : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? BorrowerConsentId { get; set; } // BorrowerConsentId
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public bool? IsAccepted { get; set; } // IsAccepted
        public string IpAddress { get; set; } // IpAddress (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent BorrowerConsent pointed by [BorrowerConsentLog].([BorrowerConsentId]) (FK_BorrowerConsentLog_BorrowerConsent)
        /// </summary>
        public virtual BorrowerConsent BorrowerConsent { get; set; } // FK_BorrowerConsentLog_BorrowerConsent

        public BorrowerConsentLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
