// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // BranchPhoneBinder

    public partial class BranchPhoneBinder : URF.Core.EF.Trackable.Entity
    {
        public int BranchId { get; set; } // BranchId (Primary key)
        public int CompanyPhoneInfoId { get; set; } // CompanyPhoneInfoId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Branch pointed by [BranchPhoneBinder].([BranchId]) (FK_BranchPhoneBinder_Branch)
        /// </summary>
        public virtual Branch Branch { get; set; } // FK_BranchPhoneBinder_Branch

        /// <summary>
        /// Parent CompanyPhoneInfo pointed by [BranchPhoneBinder].([CompanyPhoneInfoId]) (FK_BranchPhoneBinder_CompanyPhoneInfo)
        /// </summary>
        public virtual CompanyPhoneInfo CompanyPhoneInfo { get; set; } // FK_BranchPhoneBinder_CompanyPhoneInfo

        public BranchPhoneBinder()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
