// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // CustomerInfoView

    public partial class CustomerInfoView : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ContactId { get; set; } // ContactId
        public int? UserId { get; set; } // UserId
        public string Prefix { get; set; } // Prefix (Primary key) (length: 10)
        public string FirstName { get; set; } // FirstName (Primary key) (length: 300)
        public string MiddleName { get; set; } // MiddleName (Primary key) (length: 50)
        public string LastName { get; set; } // LastName (Primary key) (length: 300)
        public string Suffix { get; set; } // Suffix (Primary key) (length: 10)
        public string NickName { get; set; } // NickName (Primary key) (length: 50)
        public string Preferred { get; set; } // Preferred (Primary key) (length: 1000)
        public string Phone { get; set; } // Phone (Primary key) (length: 150)
        public string Email { get; set; } // Email (Primary key) (length: 150)
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string AllEmail { get; set; } // AllEmail
        public string AllPhone { get; set; } // AllPhone

        public CustomerInfoView()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
