// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // LeadSourceDefaultProduct
    
    public partial class LeadSourceDefaultProduct : URF.Core.EF.Trackable.Entity
    {
        public int LeadSourceId { get; set; } // LeadSourceId (Primary key)
        public int ProductTypeId { get; set; } // ProductTypeId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent LeadSource pointed by [LeadSourceDefaultProduct].([LeadSourceId]) (FK_LeadSourceDefaultProduct_LeadSource)
        /// </summary>
        public virtual LeadSource LeadSource { get; set; } // FK_LeadSourceDefaultProduct_LeadSource

        /// <summary>
        /// Parent ProductType pointed by [LeadSourceDefaultProduct].([ProductTypeId]) (FK_LeadSourceDefaultProduct_ProductType)
        /// </summary>
        public virtual ProductType ProductType { get; set; } // FK_LeadSourceDefaultProduct_ProductType

        public LeadSourceDefaultProduct()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
