// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // NoteDetail

    public partial class NoteDetail : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? NoteId { get; set; } // NoteId
        public string Message { get; set; } // Message
        public int? ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public bool IsActive { get; set; } // IsActive
        public int EntityTypeId { get; set; } // EntityTypeId
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Note pointed by [NoteDetail].([NoteId]) (FK_NoteDetail_Note)
        /// </summary>
        public virtual Note Note { get; set; } // FK_NoteDetail_Note

        /// <summary>
        /// Parent UserProfile pointed by [NoteDetail].([ModifiedBy]) (FK_NoteDetail_UserProfile)
        /// </summary>
        public virtual UserProfile UserProfile { get; set; } // FK_NoteDetail_UserProfile

        public NoteDetail()
        {
            IsActive = true;
            EntityTypeId = 69;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
