// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // ProductCatalog

    public partial class ProductCatalog : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ProductId { get; set; } // ProductId
        public string Code { get; set; } // Code (length: 100)
        public string Title { get; set; } // Title (length: 500)
        public string ShortTitle { get; set; } // ShortTitle (length: 500)
        public string Description { get; set; } // Description (length: 4000)
        public string LongDescription { get; set; } // LongDescription
        public string ImagePath { get; set; } // ImagePath (length: 200)
        public int? CmsPageId { get; set; } // CmsPageId

        // Foreign keys

        /// <summary>
        /// Parent CmsPage pointed by [ProductCatalog].([CmsPageId]) (FK_ProductCatalog_CmsPage)
        /// </summary>
        public virtual CmsPage CmsPage { get; set; } // FK_ProductCatalog_CmsPage

        /// <summary>
        /// Parent Product pointed by [ProductCatalog].([ProductId]) (FK_ProductCatalog_Product)
        /// </summary>
        public virtual Product Product { get; set; } // FK_ProductCatalog_Product

        public ProductCatalog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
