// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // RangeSetDetail
    
    public partial class RangeSetDetail : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? RangeSetId { get; set; } // RangeSetId
        public decimal? RangeFrom { get; set; } // RangeFrom
        public decimal? RangeTo { get; set; } // RangeTo
        public decimal? FixedValue { get; set; } // FixedValue
        public decimal? Percentage { get; set; } // Percentage
        public int? FormulaId { get; set; } // FormulaId

        // Foreign keys

        /// <summary>
        /// Parent Formula pointed by [RangeSetDetail].([FormulaId]) (FK_RangeSetDetail_Formula)
        /// </summary>
        public virtual Formula Formula { get; set; } // FK_RangeSetDetail_Formula

        /// <summary>
        /// Parent RangeSet pointed by [RangeSetDetail].([RangeSetId]) (FK_RangeSetDetail_RangeSet)
        /// </summary>
        public virtual RangeSet RangeSet { get; set; } // FK_RangeSetDetail_RangeSet

        public RangeSetDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
