// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // ScheduleActivityLog

    public partial class ScheduleActivityLog : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int ScheduleActivityId { get; set; } // ScheduleActivityId
        public System.DateTime? StartOnUtc { get; set; } // StartOnUtc
        public System.DateTime? EndOnUtc { get; set; } // EndOnUtc
        public bool? IsError { get; set; } // IsError
        public string Message { get; set; } // Message

        // Foreign keys

        /// <summary>
        /// Parent ScheduleActivity pointed by [ScheduleActivityLog].([ScheduleActivityId]) (FK_ScheduleActivityLog_ScheduleActivity)
        /// </summary>
        public virtual ScheduleActivity ScheduleActivity { get; set; } // FK_ScheduleActivityLog_ScheduleActivity

        public ScheduleActivityLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
