// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // SecondLien
    
    public partial class SecondLien : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? LoanRequestId { get; set; } // LoanRequestId
        public int? SecondLienTypeId { get; set; } // SecondLienTypeId
        public decimal? SecondLienBalance { get; set; } // SecondLienBalance
        public decimal? SecondLienLimit { get; set; } // SecondLienLimit
        public bool SecondLienPaidAtClosing { get; set; } // SecondLienPaidAtClosing
        public bool WasSmTaken { get; set; } // WasSmTaken

        // Foreign keys

        /// <summary>
        /// Parent LoanRequest pointed by [SecondLien].([LoanRequestId]) (FK_SecondLien_LoanRequest)
        /// </summary>
        public virtual LoanRequest LoanRequest { get; set; } // FK_SecondLien_LoanRequest

        /// <summary>
        /// Parent SecondLienType pointed by [SecondLien].([SecondLienTypeId]) (FK_SecondLien_SecondLienType)
        /// </summary>
        public virtual SecondLienType SecondLienType { get; set; } // FK_SecondLien_SecondLienType

        public SecondLien()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
