// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // SettingGroupBinder
    
    public partial class SettingGroupBinder : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? SettingId { get; set; } // SettingId
        public int? GroupId { get; set; } // GroupId
        public int? DisplayOrder { get; set; } // DisplayOrder

        // Foreign keys

        /// <summary>
        /// Parent Setting pointed by [SettingGroupBinder].([SettingId]) (FK_SettingGroupBinder_Setting)
        /// </summary>
        public virtual Setting Setting { get; set; } // FK_SettingGroupBinder_Setting

        /// <summary>
        /// Parent SettingGroup pointed by [SettingGroupBinder].([GroupId]) (FK_SettingGroupBinder_SettingGroup)
        /// </summary>
        public virtual SettingGroup SettingGroup { get; set; } // FK_SettingGroupBinder_SettingGroup

        public SettingGroupBinder()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
