// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // TemplateLocationBinder

    public partial class TemplateLocationBinder : URF.Core.EF.Trackable.Entity
    {
        public int TemplateId { get; set; } // TemplateId (Primary key)
        public int TemplateLocationId { get; set; } // TemplateLocationId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Template pointed by [TemplateLocationBinder].([TemplateId]) (FK_TemplateLocationBinder_Template)
        /// </summary>
        public virtual Template Template { get; set; } // FK_TemplateLocationBinder_Template

        public TemplateLocationBinder()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
