// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // ThirdPartyCode

    public partial class ThirdPartyCode : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ThirdPartyId { get; set; } // ThirdPartyId
        public string ElementName { get; set; } // ElementName
        public string Code { get; set; } // Code (length: 300)
        public int? EntityRefTypeId { get; set; } // EntityRefTypeId
        public int? EntityRefId { get; set; } // EntityRefId

        // Foreign keys

        /// <summary>
        /// Parent EntityType pointed by [ThirdPartyCode].([EntityRefTypeId]) (FK_ThirdPartyCode_EntityType)
        /// </summary>
        public virtual EntityType EntityType { get; set; } // FK_ThirdPartyCode_EntityType

        public ThirdPartyCode()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
