// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // VoiceMailAssignment
    
    public partial class Vortex_VoiceMailAssignment : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string RecordingSid { get; set; } // RecordingSid (length: 50)
        public int EmployeeId { get; set; } // EmployeeId
        public bool IsActive { get; set; } // IsActive
        public bool IsRead { get; set; } // IsRead
        public bool IsRecordingFileDeleted { get; set; } // IsRecordingFileDeleted
        public System.DateTime? RecordingFileToBeDeletedOn { get; set; } // RecordingFileToBeDeletedOn
        public bool? IsArchived { get; set; } // IsArchived

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [VoiceMailAssignment].([EmployeeId]) (FK_VoiceMailAssignment_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_VoiceMailAssignment_Employee

        /// <summary>
        /// Parent Vortex_Recording pointed by [VoiceMailAssignment].([RecordingSid]) (FK_VoiceMailAssignment_Recording)
        /// </summary>
        public virtual Vortex_Recording Vortex_Recording { get; set; } // FK_VoiceMailAssignment_Recording

        public Vortex_VoiceMailAssignment()
        {
            IsActive = true;
            IsRead = false;
            IsRecordingFileDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
