// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // FollowUp
    
    public partial class Vortex_FollowUp : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Message { get; set; } // Message (length: 500)
        public int? ContactId { get; set; } // ContactId
        public int EmployeeId { get; set; } // EmployeeId
        public System.DateTime? FollowUpStartDateUtc { get; set; } // FollowUpStartDateUtc
        public System.DateTime? FollowUpEndDateUtc { get; set; } // FollowUpEndDateUtc
        public System.DateTime? RemindOnUtc { get; set; } // RemindOnUtc
        public System.DateTime? FollowedUpOn { get; set; } // FollowedUpOn
        public int StatusId { get; set; } // StatusId
        public int? ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public string ContactPhone { get; set; } // ContactPhone (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Contact pointed by [FollowUp].([ContactId]) (FK_FollowUp_Contact)
        /// </summary>
        public virtual Contact Contact { get; set; } // FK_FollowUp_Contact

        /// <summary>
        /// Parent Employee pointed by [FollowUp].([EmployeeId]) (FK_FollowUp_Employee)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_FollowUp_Employee

        public Vortex_FollowUp()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
