// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    // TwilioErrorCodes

    public partial class Vortex_TwilioErrorCode : URF.Core.EF.Trackable.Entity
    {
        public string Id { get; set; } // id (Primary key via unique index ) (length: 50)
        public string Causes { get; set; } // causes (length: 500)
        public int Code { get; set; } // code
        public byte ConstPartition { get; set; } // const_partition
        public string DateCreated { get; set; } // date_created
        public string Description { get; set; } // description
        public string Docs { get; set; } // docs
        public string LastUpdated { get; set; } // last_updated
        public string LogLevel { get; set; } // log_level
        public string LogType { get; set; } // log_type
        public string Message { get; set; } // message
        public string Product { get; set; } // product
        public string SecondaryMessage { get; set; } // secondary_message
        public string Solutions { get; set; } // solutions
        public string CustomMessage { get; set; } // custom_message

        public Vortex_TwilioErrorCode()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
