// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // StatusList
    
    public partial class Vortex_StatusList : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public bool IsActive { get; set; } // IsActive
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public int? ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public bool IsSystem { get; set; } // IsSystem

        // Reverse navigation

        /// <summary>
        /// Child Vortex_AgentStatusLogs where [AgentStatusLog].[StatusId] point to this entity (FK_Vortex.LoginStatusLog_Vortex.StatusList)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Vortex_AgentStatusLog> Vortex_AgentStatusLogs { get; set; } // AgentStatusLog.FK_Vortex.LoginStatusLog_Vortex.StatusList
        /// <summary>
        /// Child Vortex_UserSettings where [UserSetting].[DefaultStatuId] point to this entity (FK_Vortex.UserSetting_StatusList)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Vortex_UserSetting> Vortex_UserSettings { get; set; } // UserSetting.FK_Vortex.UserSetting_StatusList

        public Vortex_StatusList()
        {
            CreatedOnUtc = System.DateTime.UtcNow;
            IsSystem = false;
            Vortex_AgentStatusLogs = new System.Collections.Generic.HashSet<Vortex_AgentStatusLog>();
            Vortex_UserSettings = new System.Collections.Generic.HashSet<Vortex_UserSetting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
