// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // BorrowerQuestionResponse
    
    public partial class BorrowerQuestionResponse : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int BorrowerId { get; set; } // BorrowerId
        public int QuestionId { get; set; } // QuestionId
        public string Detail { get; set; } // Detail (length: 500)
        public int TenantId { get; set; } // TenantId
        public int? SelectionOptionId { get; set; } // SelectionOptionId
        public string AnswerText { get; set; } // AnswerText (length: 150)
        public string Description { get; set; } // Description (length: 500)

        // Foreign keys

        /// <summary>
        /// Parent Borrower pointed by [BorrowerQuestionResponse].([BorrowerId]) (FK_BorrowerQuestionResponse_Borrower)
        /// </summary>
        public virtual Borrower Borrower { get; set; } // FK_BorrowerQuestionResponse_Borrower

        /// <summary>
        /// Parent Question pointed by [BorrowerQuestionResponse].([QuestionId]) (FK_BorrowerQuestionResponse_Question)
        /// </summary>
        public virtual Question Question { get; set; } // FK_BorrowerQuestionResponse_Question

        public BorrowerQuestionResponse()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
