// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // ConfigSelectionItem
    
    public partial class ConfigSelectionItem : URF.Core.EF.Trackable.Entity
    {
        public byte Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child ConfigSelections where [ConfigSelection].[SelectionId] point to this entity (FK_ConfigSelection_ConfigSelectionItem_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ConfigSelection> ConfigSelections { get; set; } // ConfigSelection.FK_ConfigSelection_ConfigSelectionItem_Id

        public ConfigSelectionItem()
        {
            ConfigSelections = new System.Collections.Generic.HashSet<ConfigSelection>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
