// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace LoanApplicationDb.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // LoanApplication
    
    public partial class LoanApplication : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string LoanNumber { get; set; } // LoanNumber (length: 50)
        public string AgencyNumber { get; set; } // AgencyNumber (length: 50)
        public int? VisitorId { get; set; } // VisitorId
        public int? OpportunityId { get; set; } // OpportunityId
        public int? BusinessUnitId { get; set; } // BusinessUnitId
        public int? CustomerId { get; set; } // CustomerId
        public int? LoanOriginatorId { get; set; } // LoanOriginatorId
        public int? LoanGoalId { get; set; } // LoanGoalId
        public int LoanPurposeId { get; set; } // LoanPurposeId
        public string OtherLoanPurpose { get; set; } // OtherLoanPurpose (length: 150)
        public int? LoanPurposeProgramId { get; set; } // LoanPurposeProgramId
        public int? CreditScoreNo { get; set; } // CreditScoreNo
        public int? ProductId { get; set; } // ProductId
        public int? LoanTypeId { get; set; } // LoanTypeId
        public string OtherLoanType { get; set; } // OtherLoanType (length: 150)
        public int? StatusId { get; set; } // StatusId
        public int? LockPeriodDays { get; set; } // LockPeriodDays
        public decimal? NoteRate { get; set; } // NoteRate
        public decimal? QualifyingRate { get; set; } // QualifyingRate
        public decimal? Price { get; set; } // Price
        public int? LoanTermMonths { get; set; } // LoanTermMonths
        public int? ProductAmortizationTypeId { get; set; } // ProductAmortizationTypeId
        public string OtherAmortization { get; set; } // OtherAmortization (length: 150)
        public bool? EscrowWaiver { get; set; } // EscrowWaiver
        public decimal? LoanAmount { get; set; } // LoanAmount
        public decimal? CashOutAmount { get; set; } // CashOutAmount
        public decimal? Deposit { get; set; } // Deposit
        public decimal? MonthlyPi { get; set; } // MonthlyPi
        public decimal? MonthlyMi { get; set; } // MonthlyMi
        public decimal? MonthlyEscrow { get; set; } // MonthlyEscrow
        public System.DateTime? ExpectedClosingDate { get; set; } // ExpectedClosingDate
        public bool? EverHadAVaLoan { get; set; } // EverHadAVaLoan
        public bool? VaLoanStatusId { get; set; } // VaLoanStatusId
        public bool? FirstTimeHomeBuyer { get; set; } // FirstTimeHomeBuyer
        public int? DtiHousing { get; set; } // DtiHousing
        public int? DtiTotal { get; set; } // DtiTotal
        public int? DocTypeId { get; set; } // DocTypeId
        public int? CompletedById { get; set; } // CompletedById
        public System.DateTime? SearchDateUtc { get; set; } // SearchDateUtc
        public int? SessionId { get; set; } // SessionId
        public string FinalXml { get; set; } // FinalXml (length: 1073741823)
        public int? EntityTypeId { get; set; } // EntityTypeId
        public bool? IsActive { get; set; } // IsActive
        public bool? IsDeleted { get; set; } // IsDeleted
        public int? SubjectPropertyDetailId { get; set; } // SubjectPropertyDetailId
        public int? NoOfPeopleLiveIn { get; set; } // NoOfPeopleLiveIn
        public decimal? AssetsUseForDownpayment { get; set; } // AssetsUseForDownpayment
        public string DownPaymentExplanation { get; set; } // DownPaymentExplanation (length: 3000)
        public int? InformationMediumId { get; set; } // InformationMediumId
        public bool? IsApplyingJointCredit { get; set; } // IsApplyingJointCredit
        public int? NoOfBorrower { get; set; } // NoOfBorrower
        public int? ProjectTypeId { get; set; } // ProjectTypeId
        public byte[] LoanApplicationFlowState { get; set; } // LoanApplicationFlowState
        public string EncompassId { get; set; } // EncompassId (length: 50)
        public string EncompassNumber { get; set; } // EncompassNumber (length: 50)
        public string ByteLoanNumber { get; set; } // ByteLoanNumber (length: 50)
        public string ByteFileName { get; set; } // ByteFileName (length: 255)
        public System.DateTime? EncompassPostDateUtc { get; set; } // EncompassPostDateUtc
        public System.DateTime? BytePostDateUtc { get; set; } // BytePostDateUtc
        public int? ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public int? MilestoneId { get; set; } // MilestoneId
        public int? LosMilestoneId { get; set; } // LosMilestoneId
        public int TenantId { get; set; } // TenantId
        public int? BranchId { get; set; } // BranchId
        public int? LoanOfficerId { get; set; } // LoanOfficerId
        public int? UserId { get; set; } // UserId
        public string SettingHash { get; set; } // SettingHash (length: 200)
        public string State { get; set; } // State
        public bool? IsPropertyIdentified { get; set; } // IsPropertyIdentified
        public bool? IsEarnestMoneyProvided { get; set; } // IsEarnestMoneyProvided
        public string Comments { get; set; } // Comments

        // Reverse navigation

        /// <summary>
        /// Child Borrowers where [Borrower].[LoanApplicationId] point to this entity (FK_Borrower_LoanApplication)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Borrower> Borrowers { get; set; } // Borrower.FK_Borrower_LoanApplication
        /// <summary>
        /// Child BorrowerConsents where [BorrowerConsent].[LoanApplicationId] point to this entity (FK_BorrowerConsent_LoanApplication)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BorrowerConsent> BorrowerConsents { get; set; } // BorrowerConsent.FK_BorrowerConsent_LoanApplication
        /// <summary>
        /// Child VaDetails where [VaDetails].[LoanApplicationId] point to this entity (FK_VaDetails_LoanApplication)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<VaDetail> VaDetails { get; set; } // VaDetails.FK_VaDetails_LoanApplication

        // Foreign keys

        /// <summary>
        /// Parent LoanGoal pointed by [LoanApplication].([LoanGoalId]) (FK_LoanApplication_LoanGoal)
        /// </summary>
        public virtual LoanGoal LoanGoal { get; set; } // FK_LoanApplication_LoanGoal

        /// <summary>
        /// Parent LoanPurpose pointed by [LoanApplication].([LoanPurposeId]) (FK_LoanApplication_LoanPurpose)
        /// </summary>
        public virtual LoanPurpose LoanPurpose { get; set; } // FK_LoanApplication_LoanPurpose

        /// <summary>
        /// Parent LoanPurposeProgram pointed by [LoanApplication].([LoanPurposeProgramId]) (FK_LoanApplication_LoanPurposeProgram)
        /// </summary>
        public virtual LoanPurposeProgram LoanPurposeProgram { get; set; } // FK_LoanApplication_LoanPurposeProgram

        /// <summary>
        /// Parent LoanType pointed by [LoanApplication].([LoanTypeId]) (FK_LoanApplication_LoanType)
        /// </summary>
        public virtual LoanType LoanType { get; set; } // FK_LoanApplication_LoanType

        /// <summary>
        /// Parent ProductAmortizationType pointed by [LoanApplication].([ProductAmortizationTypeId]) (FK_LoanApplication_ProductAmortizationType)
        /// </summary>
        public virtual ProductAmortizationType ProductAmortizationType { get; set; } // FK_LoanApplication_ProductAmortizationType

        /// <summary>
        /// Parent ProjectType pointed by [LoanApplication].([ProjectTypeId]) (FK_LoanApplication_ProjectType)
        /// </summary>
        public virtual ProjectType ProjectType { get; set; } // FK_LoanApplication_ProjectType

        /// <summary>
        /// Parent PropertyInfo pointed by [LoanApplication].([SubjectPropertyDetailId]) (FK_LoanApplication_PropertyInfo)
        /// </summary>
        public virtual PropertyInfo PropertyInfo { get; set; } // FK_LoanApplication_PropertyInfo

        public LoanApplication()
        {
            EntityTypeId = 18;
            IsActive = true;
            IsDeleted = false;
            Borrowers = new System.Collections.Generic.HashSet<Borrower>();
            BorrowerConsents = new System.Collections.Generic.HashSet<BorrowerConsent>();
            VaDetails = new System.Collections.Generic.HashSet<VaDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
