//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/17/2020 9:13:55 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace LosIntegration.Entity.Models
{
    public partial class ExternalOriginator : URF.Core.EF.Trackable.Entity {

        public ExternalOriginator()
        {
            this.Mappings = new List<Mapping>();
            OnCreated();
        }

        public virtual short Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual IList<Mapping> Mappings
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
