// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // PasswordPolicy
    
    public partial class PasswordPolicy : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int TenantId { get; set; } // TenantId
        public int MinimumLength { get; set; } // MinimumLength
        public int MaximumLength { get; set; } // MaximumLength
        public bool ViewPassword { get; set; } // ViewPassword
        public int IncorrectPasswordCount { get; set; } // IncorrectPasswordCount
        public bool Enable2Fa { get; set; } // Enable2FA
        public int AccountLockDurationInMinutes { get; set; } // AccountLockDurationInMinutes
        public int ForgotTokenExpiryInMinutes { get; set; } // ForgotTokenExpiryInMinutes

        public PasswordPolicy()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
