// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // spt_values
    
    public partial class SptValue : URF.Core.EF.Trackable.Entity
    {
        public string Name { get; set; } // name (length: 35)
        public int Number { get; set; } // number (Primary key)
        public string Type { get; set; } // type (Primary key) (length: 3)
        public int? Low { get; set; } // low
        public int? High { get; set; } // high
        public int? Status { get; set; } // status

        public SptValue()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
