// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // UserRoleBinder
    
    public partial class UserRoleBinder : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int RoleId { get; set; } // RoleId

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [UserRoleBinder].([RoleId]) (FK_UserRoleBinder_Role_Id)
        /// </summary>
        public virtual Role Role { get; set; } // FK_UserRoleBinder_Role_Id

        /// <summary>
        /// Parent User pointed by [UserRoleBinder].([UserId]) (FK_UserRoleBinder_User_Id)
        /// </summary>
        public virtual User User { get; set; } // FK_UserRoleBinder_User_Id

        public UserRoleBinder()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
