// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // BorrowerProperty
    
    public partial class BorrowerPropertyMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<BorrowerProperty>
    {
        public void Configure(EntityTypeBuilder<BorrowerProperty> builder)
        {
            builder.ToTable("BorrowerProperty", "dbo");
            builder.HasKey(x => new { x.BorrowerId, x.PropertyInfoId });

            builder.Property(x => x.BorrowerId).HasColumnName(@"BorrowerId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PropertyInfoId).HasColumnName(@"PropertyInfoId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Borrower).WithMany(b => b.BorrowerProperties).HasForeignKey(c => c.BorrowerId).OnDelete(DeleteBehavior.SetNull); // FK_BorrowerProperty_Borrower
            builder.HasOne(a => a.PropertyInfo).WithMany(b => b.BorrowerProperties).HasForeignKey(c => c.PropertyInfoId).OnDelete(DeleteBehavior.SetNull); // FK_BorrowerProperty_PropertyInfo
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
