// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // BusinessUnitEmail
    
    public partial class BusinessUnitEmailMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<BusinessUnitEmail>
    {
        public void Configure(EntityTypeBuilder<BusinessUnitEmail> builder)
        {
            builder.ToTable("BusinessUnitEmail", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.BusinessUnitId).HasColumnName(@"BusinessUnitId").HasColumnType("int").IsRequired();
            builder.Property(x => x.EmailAccountId).HasColumnName(@"EmailAccountId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TypeId).HasColumnName(@"TypeId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.BusinessUnit).WithMany(b => b.BusinessUnitEmails).HasForeignKey(c => c.BusinessUnitId).OnDelete(DeleteBehavior.SetNull); // FK_BusinessUnitEmail_BusinessUnit
            builder.HasOne(a => a.EmailAccount).WithMany(b => b.BusinessUnitEmails).HasForeignKey(c => c.EmailAccountId).OnDelete(DeleteBehavior.SetNull); // FK_BusinessUnitEmail_EmailAccount
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
