// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // LoanRequestProductType
    
    public partial class LoanRequestProductTypeMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<LoanRequestProductType>
    {
        public void Configure(EntityTypeBuilder<LoanRequestProductType> builder)
        {
            builder.ToTable("LoanRequestProductType", "dbo");
            builder.HasKey(x => new { x.LoanRequestId, x.ProductTypeId });

            builder.Property(x => x.LoanRequestId).HasColumnName(@"LoanRequestId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProductTypeId).HasColumnName(@"ProductTypeId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.LoanRequest).WithMany(b => b.LoanRequestProductTypes).HasForeignKey(c => c.LoanRequestId).OnDelete(DeleteBehavior.SetNull); // FK_LoanRequestProductType_LoanRequest
            builder.HasOne(a => a.ProductType).WithMany(b => b.LoanRequestProductTypes).HasForeignKey(c => c.ProductTypeId).OnDelete(DeleteBehavior.SetNull); // FK_LoanRequestProductType_ProductType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
