// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // MarksmanLeadDetail
    
    public partial class MarksmanLeadDetailMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<MarksmanLeadDetail>
    {
        public void Configure(EntityTypeBuilder<MarksmanLeadDetail> builder)
        {
            builder.ToTable("MarksmanLeadDetail", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProspectId).HasColumnName(@"ProspectId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectTrackingId).HasColumnName(@"ProspectTrackingId").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectFirstName).HasColumnName(@"ProspectFirstName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectMiddleName).HasColumnName(@"ProspectMiddleName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLastName).HasColumnName(@"ProspectLastName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectSsn).HasColumnName(@"ProspectSsn").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectAddress1).HasColumnName(@"ProspectAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectAddress2).HasColumnName(@"ProspectAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCity).HasColumnName(@"ProspectCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectState).HasColumnName(@"ProspectState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectZip).HasColumnName(@"ProspectZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectEmail).HasColumnName(@"ProspectEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectHomePhone).HasColumnName(@"ProspectHomePhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectMobilePhone).HasColumnName(@"ProspectMobilePhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectWorkPhone).HasColumnName(@"ProspectWorkPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectDob).HasColumnName(@"ProspectDob").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCustomerId).HasColumnName(@"ProspectCustomerId").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectSource).HasColumnName(@"ProspectSource").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectStatus).HasColumnName(@"ProspectStatus").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLoanAmount).HasColumnName(@"ProspectLoanAmount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPurchasePrice).HasColumnName(@"ProspectPurchasePrice").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDownPayment).HasColumnName(@"ProspectDownPayment").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLockInPeriod).HasColumnName(@"ProspectLockInPeriod").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLoanPurpose).HasColumnName(@"ProspectLoanPurpose").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLtv).HasColumnName(@"ProspectLtv").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectOccupancy).HasColumnName(@"ProspectOccupancy").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectFico).HasColumnName(@"ProspectFico").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPropertyAddress1).HasColumnName(@"ProspectPropertyAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyAddress2).HasColumnName(@"ProspectPropertyAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyCity).HasColumnName(@"ProspectPropertyCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyState).HasColumnName(@"ProspectPropertyState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyZip).HasColumnName(@"ProspectPropertyZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyCounty).HasColumnName(@"ProspectPropertyCounty").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLoanOfficerId).HasColumnName(@"ProspectLoanOfficerId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLoanOfficerName).HasColumnName(@"ProspectLoanOfficerName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLoanOfficerEmail).HasColumnName(@"ProspectLoanOfficerEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLoanOfficerUsername).HasColumnName(@"ProspectLoanOfficerUsername").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLoanOfficerPhone).HasColumnName(@"ProspectLoanOfficerPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectRealtorName).HasColumnName(@"ProspectRealtorName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectRealtorPhone).HasColumnName(@"ProspectRealtorPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectRealtorEmail).HasColumnName(@"ProspectRealtorEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectProjectedCloseDate).HasColumnName(@"ProspectProjectedCloseDate").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectFoundAHome).HasColumnName(@"ProspectFoundAHome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectSellersName).HasColumnName(@"ProspectSellersName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectSellersEmail).HasColumnName(@"ProspectSellersEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectOriginalAssignedLo).HasColumnName(@"ProspectOriginalAssignedLo").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectLastAssignedDate).HasColumnName(@"ProspectLastAssignedDate").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbFico).HasColumnName(@"ProspectCbFico").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.CurrentMortgageBalance).HasColumnName(@"CurrentMortgageBalance").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.CurrentMortgageRate).HasColumnName(@"CurrentMortgageRate").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.CurrentMortgagePayment).HasColumnName(@"CurrentMortgagePayment").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.AgencyCaseNum).HasColumnName(@"AgencyCaseNum").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.LenderCaseNum).HasColumnName(@"LenderCaseNum").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.LegalDescription).HasColumnName(@"LegalDescription").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.YearLotAcquired).HasColumnName(@"YearLotAcquired").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.OriginalCost).HasColumnName(@"OriginalCost").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.AmountLien).HasColumnName(@"AmountLien").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.PresentValue).HasColumnName(@"PresentValue").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.PurposeRefi).HasColumnName(@"PurposeRefi").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.MannerTitleHeld).HasColumnName(@"MannerTitleHeld").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.PropertyImprovements).HasColumnName(@"PropertyImprovements").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ImprovementMade).HasColumnName(@"ImprovementMade").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.CostOfImprovements).HasColumnName(@"CostOfImprovements").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectDependents).HasColumnName(@"ProspectDependents").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectDependentsAge).HasColumnName(@"ProspectDependentsAge").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectYearsInSchool).HasColumnName(@"ProspectYearsInSchool").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectMaritalStatus).HasColumnName(@"ProspectMaritalStatus").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectSex).HasColumnName(@"ProspectSex").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectRace).HasColumnName(@"ProspectRace").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectEthnicity).HasColumnName(@"ProspectEthnicity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbDependents).HasColumnName(@"ProspectCbDependents").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbDependentsAge).HasColumnName(@"ProspectCbDependentsAge").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbYearsInSchool).HasColumnName(@"ProspectCbYearsInSchool").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbMaritalStatus).HasColumnName(@"ProspectCbMaritalStatus").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbSex).HasColumnName(@"ProspectCbSex").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbRace).HasColumnName(@"ProspectCbRace").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbEthnicity).HasColumnName(@"ProspectCbEthnicity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectEstateHeld).HasColumnName(@"ProspectEstateHeld").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectExpirationDate).HasColumnName(@"ProspectExpirationDate").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectDownPaymentType).HasColumnName(@"ProspectDownPaymentType").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectProduct1VendorId).HasColumnName(@"ProspectProduct1VendorId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct1Id).HasColumnName(@"ProspectProduct1Id").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct1Rate).HasColumnName(@"ProspectProduct1Rate").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct1Price).HasColumnName(@"ProspectProduct1Price").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct1Apr).HasColumnName(@"ProspectProduct1Apr").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct1LtProductName).HasColumnName(@"ProspectProduct1LtProductName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectProduct1MonthlyPayment).HasColumnName(@"ProspectProduct1MonthlyPayment").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct2VendorId).HasColumnName(@"ProspectProduct2VendorId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct2Id).HasColumnName(@"ProspectProduct2Id").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct2Rate).HasColumnName(@"ProspectProduct2Rate").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct2Price).HasColumnName(@"ProspectProduct2Price").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct2Apr).HasColumnName(@"ProspectProduct2Apr").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct2LtProductName).HasColumnName(@"ProspectProduct2LtProductName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectProduct2MonthlyPayment).HasColumnName(@"ProspectProduct2MonthlyPayment").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct3VendorId).HasColumnName(@"ProspectProduct3VendorId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct3Id).HasColumnName(@"ProspectProduct3Id").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectProduct3Rate).HasColumnName(@"ProspectProduct3Rate").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct3Price).HasColumnName(@"ProspectProduct3Price").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct3Apr).HasColumnName(@"ProspectProduct3Apr").HasColumnType("decimal(18,3)").IsRequired(false);
            builder.Property(x => x.ProspectProduct3LtProductName).HasColumnName(@"ProspectProduct3LtProductName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectProduct3MonthlyPayment).HasColumnName(@"ProspectProduct3MonthlyPayment").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrResOwnOrRent).HasColumnName(@"ProspectCurrResOwnOrRent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrResNumberOfYears).HasColumnName(@"ProspectCurrResNumberOfYears").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrResNumberOfMonths).HasColumnName(@"ProspectCurrResNumberOfMonths").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrResAddress1).HasColumnName(@"ProspectCurrResAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrResAddress2).HasColumnName(@"ProspectCurrResAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrResCity).HasColumnName(@"ProspectCurrResCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrResState).HasColumnName(@"ProspectCurrResState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrResZip).HasColumnName(@"ProspectCurrResZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevResOwnOrRent).HasColumnName(@"ProspectPrevResOwnOrRent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevResNumberOfYears).HasColumnName(@"ProspectPrevResNumberOfYears").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevResNumberOfMonths).HasColumnName(@"ProspectPrevResNumberOfMonths").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevResAddress1).HasColumnName(@"ProspectPrevResAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevResAddress2).HasColumnName(@"ProspectPrevResAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevResCity).HasColumnName(@"ProspectPrevResCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevResState).HasColumnName(@"ProspectPrevResState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevResZip).HasColumnName(@"ProspectPrevResZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpEmployerName).HasColumnName(@"ProspectCurrEmpEmployerName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpMonthsOnJob).HasColumnName(@"ProspectCurrEmpMonthsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrEmpYearsOnJob).HasColumnName(@"ProspectCurrEmpYearsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrEmpYearsOfExperience).HasColumnName(@"ProspectCurrEmpYearsOfExperience").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrEmpTitle).HasColumnName(@"ProspectCurrEmpTitle").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpPhone).HasColumnName(@"ProspectCurrEmpPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpPhoneExtension).HasColumnName(@"ProspectCurrEmpPhoneExtension").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpIsSelfEmployed).HasColumnName(@"ProspectCurrEmpIsSelfEmployed").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCurrEmpAddress1).HasColumnName(@"ProspectCurrEmpAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpAddress2).HasColumnName(@"ProspectCurrEmpAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpCity).HasColumnName(@"ProspectCurrEmpCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpState).HasColumnName(@"ProspectCurrEmpState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpZip).HasColumnName(@"ProspectCurrEmpZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCurrEmpStartDate).HasColumnName(@"ProspectCurrEmpStartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCurrEmpEndDate).HasColumnName(@"ProspectCurrEmpEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpEmployerName).HasColumnName(@"ProspectPrevEmpEmployerName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpMonthsOnJob).HasColumnName(@"ProspectPrevEmpMonthsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpYearsOnJob).HasColumnName(@"ProspectPrevEmpYearsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpYearsOfExperience).HasColumnName(@"ProspectPrevEmpYearsOfExperience").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpTitle).HasColumnName(@"ProspectPrevEmpTitle").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpPhone).HasColumnName(@"ProspectPrevEmpPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpPhoneExtension).HasColumnName(@"ProspectPrevEmpPhoneExtension").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpIsSelfEmployed).HasColumnName(@"ProspectPrevEmpIsSelfEmployed").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpAddress1).HasColumnName(@"ProspectPrevEmpAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpAddress2).HasColumnName(@"ProspectPrevEmpAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpCity).HasColumnName(@"ProspectPrevEmpCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpState).HasColumnName(@"ProspectPrevEmpState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpZip).HasColumnName(@"ProspectPrevEmpZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPrevEmpStartDate).HasColumnName(@"ProspectPrevEmpStartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectPrevEmpEndDate).HasColumnName(@"ProspectPrevEmpEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCondo).HasColumnName(@"ProspectCondo").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectUnits).HasColumnName(@"ProspectUnits").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectWaiveEscrow).HasColumnName(@"ProspectWaiveEscrow").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectSecondaryFinancing).HasColumnName(@"ProspectSecondaryFinancing").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectManufacturedHome).HasColumnName(@"ProspectManufacturedHome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectAddDate).HasColumnName(@"ProspectAddDate").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCreditRating).HasColumnName(@"ProspectCreditRating").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectBankruptcy).HasColumnName(@"ProspectBankruptcy").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectMonthlyIncome).HasColumnName(@"ProspectMonthlyIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectMonthlyDebt).HasColumnName(@"ProspectMonthlyDebt").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectOccupationalStatus).HasColumnName(@"ProspectOccupationalStatus").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectFilters).HasColumnName(@"ProspectFilters").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectPropertyYearBuilt).HasColumnName(@"ProspectPropertyYearBuilt").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectContactPreference).HasColumnName(@"ProspectContactPreference").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectFirstTimeHomeBuyer).HasColumnName(@"ProspectFirstTimeHomeBuyer").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectIncomeType).HasColumnName(@"ProspectIncomeType").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectIncomeVerify).HasColumnName(@"ProspectIncomeVerify").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectChapter7Years).HasColumnName(@"ProspectChapter7Years").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectChapter13Years).HasColumnName(@"ProspectChapter13Years").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectForeclosureYears).HasColumnName(@"ProspectForeclosureYears").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLate30).HasColumnName(@"ProspectLate30").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLate60).HasColumnName(@"ProspectLate60").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLate90).HasColumnName(@"ProspectLate90").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectLate120).HasColumnName(@"ProspectLate120").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectGrossDisposableIncome).HasColumnName(@"ProspectGrossDisposableIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationBaseIncome).HasColumnName(@"ProspectDeclarationBaseIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationBonuses).HasColumnName(@"ProspectDeclarationBonuses").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationNetRentalIncome).HasColumnName(@"ProspectDeclarationNetRentalIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationOvertime).HasColumnName(@"ProspectDeclarationOvertime").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationCommissions).HasColumnName(@"ProspectDeclarationCommissions").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationInstallmentDebts).HasColumnName(@"ProspectDeclarationInstallmentDebts").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclarationContinuingDebts).HasColumnName(@"ProspectDeclarationContinuingDebts").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration1).HasColumnName(@"ProspectDeclaration1").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration2).HasColumnName(@"ProspectDeclaration2").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration3).HasColumnName(@"ProspectDeclaration3").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration4).HasColumnName(@"ProspectDeclaration4").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration5).HasColumnName(@"ProspectDeclaration5").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration6).HasColumnName(@"ProspectDeclaration6").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration7).HasColumnName(@"ProspectDeclaration7").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration8).HasColumnName(@"ProspectDeclaration8").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration9).HasColumnName(@"ProspectDeclaration9").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration10).HasColumnName(@"ProspectDeclaration10").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectDeclaration11).HasColumnName(@"ProspectDeclaration11").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbFirstName).HasColumnName(@"ProspectCbFirstName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbMiddleName).HasColumnName(@"ProspectCbMiddleName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbLastName).HasColumnName(@"ProspectCbLastName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbEmail).HasColumnName(@"ProspectCbEmail").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbHomePhone).HasColumnName(@"ProspectCbHomePhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbMobilePhone).HasColumnName(@"ProspectCbMobilePhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbWorkPhone).HasColumnName(@"ProspectCbWorkPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbSsn).HasColumnName(@"ProspectCbSsn").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbDob).HasColumnName(@"ProspectCbDob").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrResOwnOrRent).HasColumnName(@"ProspectCbCurrResOwnOrRent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrResNumberOfYears).HasColumnName(@"ProspectCbCurrResNumberOfYears").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrResNumberOfMonths).HasColumnName(@"ProspectCbCurrResNumberOfMonths").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrResAddress1).HasColumnName(@"ProspectCbCurrResAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrResAddress2).HasColumnName(@"ProspectCbCurrResAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrResCity).HasColumnName(@"ProspectCbCurrResCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrResState).HasColumnName(@"ProspectCbCurrResState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrResZip).HasColumnName(@"ProspectCbCurrResZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevResOwnOrRent).HasColumnName(@"ProspectCbPrevResOwnOrRent").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevResNumberOfYears).HasColumnName(@"ProspectCbPrevResNumberOfYears").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevResNumberOfMonths).HasColumnName(@"ProspectCbPrevResNumberOfMonths").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevResAddress1).HasColumnName(@"ProspectCbPrevResAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevResAddress2).HasColumnName(@"ProspectCbPrevResAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevResCity).HasColumnName(@"ProspectCbPrevResCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevResState).HasColumnName(@"ProspectCbPrevResState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevResZip).HasColumnName(@"ProspectCbPrevResZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpEmployerName).HasColumnName(@"ProspectCbCurrEmpEmployerName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpMonthsOnJob).HasColumnName(@"ProspectCbCurrEmpMonthsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrEmpYearsOnJob).HasColumnName(@"ProspectCbCurrEmpYearsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrEmpYearsOfExperience).HasColumnName(@"ProspectCbCurrEmpYearsOfExperience").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrEmpTitle).HasColumnName(@"ProspectCbCurrEmpTitle").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpPhone).HasColumnName(@"ProspectCbCurrEmpPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpPhoneExtension).HasColumnName(@"ProspectCbCurrEmpPhoneExtension").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpIsSelfEmployed).HasColumnName(@"ProspectCbCurrEmpIsSelfEmployed").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrEmpAddress1).HasColumnName(@"ProspectCbCurrEmpAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpAddress2).HasColumnName(@"ProspectCbCurrEmpAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpCity).HasColumnName(@"ProspectCbCurrEmpCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpState).HasColumnName(@"ProspectCbCurrEmpState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpZip).HasColumnName(@"ProspectCbCurrEmpZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbCurrEmpStartDate).HasColumnName(@"ProspectCbCurrEmpStartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCbCurrEmpEndDate).HasColumnName(@"ProspectCbCurrEmpEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpEmployerName).HasColumnName(@"ProspectCbPrevEmpEmployerName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpMonthsOnJob).HasColumnName(@"ProspectCbPrevEmpMonthsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpYearsOnJob).HasColumnName(@"ProspectCbPrevEmpYearsOnJob").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpYearsOfExperience).HasColumnName(@"ProspectCbPrevEmpYearsOfExperience").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpTitle).HasColumnName(@"ProspectCbPrevEmpTitle").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpPhone).HasColumnName(@"ProspectCbPrevEmpPhone").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpPhoneExtension).HasColumnName(@"ProspectCbPrevEmpPhoneExtension").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpIsSelfEmployed).HasColumnName(@"ProspectCbPrevEmpIsSelfEmployed").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpAddress1).HasColumnName(@"ProspectCbPrevEmpAddress1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpAddress2).HasColumnName(@"ProspectCbPrevEmpAddress2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpCity).HasColumnName(@"ProspectCbPrevEmpCity").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpState).HasColumnName(@"ProspectCbPrevEmpState").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpZip).HasColumnName(@"ProspectCbPrevEmpZip").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCbPrevEmpStartDate).HasColumnName(@"ProspectCbPrevEmpStartDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCbPrevEmpEndDate).HasColumnName(@"ProspectCbPrevEmpEndDate").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationBaseIncome).HasColumnName(@"ProspectCbDeclarationBaseIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationBonuses).HasColumnName(@"ProspectCbDeclarationBonuses").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationNetRentalIncome).HasColumnName(@"ProspectCbDeclarationNetRentalIncome").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationOvertime).HasColumnName(@"ProspectCbDeclarationOvertime").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationCommissions).HasColumnName(@"ProspectCbDeclarationCommissions").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationInstallmentDebts).HasColumnName(@"ProspectCbDeclarationInstallmentDebts").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclarationContinuingDebts).HasColumnName(@"ProspectCbDeclarationContinuingDebts").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration1).HasColumnName(@"ProspectCbDeclaration1").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration2).HasColumnName(@"ProspectCbDeclaration2").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration3).HasColumnName(@"ProspectCbDeclaration3").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration4).HasColumnName(@"ProspectCbDeclaration4").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration5).HasColumnName(@"ProspectCbDeclaration5").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration6).HasColumnName(@"ProspectCbDeclaration6").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration7).HasColumnName(@"ProspectCbDeclaration7").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration8).HasColumnName(@"ProspectCbDeclaration8").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration9).HasColumnName(@"ProspectCbDeclaration9").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration10).HasColumnName(@"ProspectCbDeclaration10").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectCbDeclaration11).HasColumnName(@"ProspectCbDeclaration11").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.ProspectSourceName).HasColumnName(@"ProspectSourceName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName1).HasColumnName(@"ProspectCfName1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue1).HasColumnName(@"ProspectCfValue1").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName2).HasColumnName(@"ProspectCfName2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue2).HasColumnName(@"ProspectCfValue2").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName3).HasColumnName(@"ProspectCfName3").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue3).HasColumnName(@"ProspectCfValue3").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName4).HasColumnName(@"ProspectCfName4").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue4).HasColumnName(@"ProspectCfValue4").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName5).HasColumnName(@"ProspectCfName5").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue5).HasColumnName(@"ProspectCfValue5").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName6).HasColumnName(@"ProspectCfName6").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue6).HasColumnName(@"ProspectCfValue6").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName7).HasColumnName(@"ProspectCfName7").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue7).HasColumnName(@"ProspectCfValue7").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName8).HasColumnName(@"ProspectCfName8").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue8).HasColumnName(@"ProspectCfValue8").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName9).HasColumnName(@"ProspectCfName9").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue9).HasColumnName(@"ProspectCfValue9").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfName10).HasColumnName(@"ProspectCfName10").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectCfValue10).HasColumnName(@"ProspectCfValue10").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.BranchName).HasColumnName(@"BranchName").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.ProspectNotes).HasColumnName(@"ProspectNotes").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.CallDisposition).HasColumnName(@"CallDisposition").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(250);

            // Foreign keys
            builder.HasOne(a => a.MarksmanLead).WithOne(b => b.MarksmanLeadDetail).HasForeignKey<MarksmanLeadDetail>(c => c.Id).OnDelete(DeleteBehavior.SetNull); // FK_MarksmanLeadDetail_MarksmanLead
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
