// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // OppAssignLog
    
    public partial class OppAssignLogMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<OppAssignLog>
    {
        public void Configure(EntityTypeBuilder<OppAssignLog> builder)
        {
            builder.ToTable("OppAssignLog", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.OpportunityId).HasColumnName(@"OpportunityId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.DateUtc).HasColumnName(@"DateUtc").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsAutoAssigned).HasColumnName(@"IsAutoAssigned").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.AssignedById).HasColumnName(@"AssignedById").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IsPicked).HasColumnName(@"IsPicked").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsBroadcast).HasColumnName(@"IsBroadcast").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.IsPitched).HasColumnName(@"IsPitched").HasColumnType("bit").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Employee).WithMany(b => b.OppAssignLogs).HasForeignKey(c => c.EmployeeId).OnDelete(DeleteBehavior.SetNull); // FK_OppAssignLog_Employee
            builder.HasOne(a => a.Opportunity).WithMany(b => b.OppAssignLogs).HasForeignKey(c => c.OpportunityId).OnDelete(DeleteBehavior.SetNull); // FK_OppAssignLog_Opportunity
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
