// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // OwnerShipInterest
    
    public partial class OwnerShipInterestMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<OwnerShipInterest>
    {
        public void Configure(EntityTypeBuilder<OwnerShipInterest> builder)
        {
            builder.ToTable("OwnerShipInterest", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.BorrowerId).HasColumnName(@"BorrowerId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.PropertyTypeId).HasColumnName(@"PropertyTypeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TitleHeldWithId).HasColumnName(@"TitleHeldWithId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Borrower).WithMany(b => b.OwnerShipInterests).HasForeignKey(c => c.BorrowerId).OnDelete(DeleteBehavior.SetNull); // FK_OwnerShipInterest_Borrower
            builder.HasOne(a => a.PropertyType).WithMany(b => b.OwnerShipInterests).HasForeignKey(c => c.PropertyTypeId).OnDelete(DeleteBehavior.SetNull); // FK_OwnerShipInterest_PropertyType
            builder.HasOne(a => a.TitleHeldWith).WithMany(b => b.OwnerShipInterests).HasForeignKey(c => c.TitleHeldWithId).OnDelete(DeleteBehavior.SetNull); // FK_OwnerShipInterest_TitleHeldWith
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
