// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // ScheduleActivityLog
    
    public partial class ScheduleActivityLogMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<ScheduleActivityLog>
    {
        public void Configure(EntityTypeBuilder<ScheduleActivityLog> builder)
        {
            builder.ToTable("ScheduleActivityLog", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.ScheduleActivityId).HasColumnName(@"ScheduleActivityId").HasColumnType("int").IsRequired();
            builder.Property(x => x.StartOnUtc).HasColumnName(@"StartOnUtc").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.EndOnUtc).HasColumnName(@"EndOnUtc").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.IsError).HasColumnName(@"IsError").HasColumnType("bit").IsRequired(false);
            builder.Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar(max)").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ScheduleActivity).WithMany(b => b.ScheduleActivityLogs).HasForeignKey(c => c.ScheduleActivityId).OnDelete(DeleteBehavior.SetNull); // FK_ScheduleActivityLog_ScheduleActivity
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
