// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // AgentStatus
    
    public partial class Vortex_AgentStatuMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Vortex_AgentStatu>
    {
        public void Configure(EntityTypeBuilder<Vortex_AgentStatu> builder)
        {
            builder.ToTable("AgentStatus", "Vortex");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.StatusId).HasColumnName(@"StatusId").HasColumnType("int").IsRequired();
            builder.Property(x => x.TimeStamp).HasColumnName(@"TimeStamp").HasColumnType("datetime2").IsRequired();
            builder.Property(x => x.UserSessionId).HasColumnName(@"UserSessionId").HasColumnType("bigint").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Vortex_StatusList).WithMany(b => b.Vortex_AgentStatus).HasForeignKey(c => c.StatusId).OnDelete(DeleteBehavior.SetNull); // FK_Vortex.AgentStatus_Vortex.StatusList
            builder.HasOne(a => a.Vortex_UserSession).WithMany(b => b.Vortex_AgentStatus).HasForeignKey(c => c.UserSessionId).OnDelete(DeleteBehavior.SetNull); // FK_Vortex.AgentStatus_Vortex.UserSession
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
