using AutoMapper;
using RainMaker.Entity.Models;

namespace Rainmaker.API
{
    public class AutoMapperConfig
    {
        public static MapperConfiguration GetConfiguration()
        {
            var config = new MapperConfiguration(configure: cfg =>
            {
                cfg.CreateMap<AccountType, Model.ServiceResponseModels.Rainmaker.AccountType>();
                // cfg.CreateMap<RainMaker.Entity.Models.Acl, Rainmaker.Model.ServiceResponseModels.LoanApplication.Acl>();
                // cfg.CreateMap<RainMaker.Entity.Models.Activity, Rainmaker.Model.ServiceResponseModels.LoanApplication.Activity>();
                // cfg.CreateMap<RainMaker.Entity.Models.ActivitySubscriptionBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.ActivitySubscriptionBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.ActivityType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ActivityType>();
                cfg.CreateMap<AddressInfo, Model.ServiceResponseModels.Rainmaker.AddressInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.Adjustment, Rainmaker.Model.ServiceResponseModels.LoanApplication.Adjustment>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsGeoLocation, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsGeoLocation>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsPageLocation, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsPageLocation>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsPromotion, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsPromotion>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsSize, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsSize>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsSource, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsSource>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsSourceMessage, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsSourceMessage>();
                // cfg.CreateMap<RainMaker.Entity.Models.AdsType, Rainmaker.Model.ServiceResponseModels.LoanApplication.AdsType>();
                // cfg.CreateMap<RainMaker.Entity.Models.Agency, Rainmaker.Model.ServiceResponseModels.LoanApplication.Agency>();
                cfg.CreateMap<AssetBorrowerBinder, Model.ServiceResponseModels.Rainmaker.AssetBorrowerBinder>();
                cfg.CreateMap<AssetType, Model.ServiceResponseModels.Rainmaker.AssetType>();
                // cfg.CreateMap<RainMaker.Entity.Models.BankRuptcy, Rainmaker.Model.ServiceResponseModels.LoanApplication.BankRuptcy>();
                cfg.CreateMap<Borrower, Model.ServiceResponseModels.Rainmaker.Borrower>();
                cfg.CreateMap<BorrowerAccount, Model.ServiceResponseModels.Rainmaker.BorrowerAccount>();
                cfg.CreateMap<BorrowerAccountBinder, Model.ServiceResponseModels.Rainmaker.BorrowerAccountBinder>();
                cfg.CreateMap<BorrowerAsset, Model.ServiceResponseModels.Rainmaker.BorrowerAsset>();
                cfg.CreateMap<BorrowerBankRuptcy, Model.ServiceResponseModels.Rainmaker.BorrowerBankRuptcy>();
                // cfg.CreateMap<RainMaker.Entity.Models.BorrowerConsent, Rainmaker.Model.ServiceResponseModels.LoanApplication.BorrowerConsent>();
                // cfg.CreateMap<RainMaker.Entity.Models.BorrowerConsentLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.BorrowerConsentLog>();
                cfg.CreateMap<BorrowerLiability, Model.ServiceResponseModels.Rainmaker.BorrowerLiability>();
                cfg.CreateMap<BorrowerProperty, Model.ServiceResponseModels.Rainmaker.BorrowerProperty>();
                cfg.CreateMap<BorrowerQuestionResponse, Model.ServiceResponseModels.Rainmaker.BorrowerQuestionResponse>();
                cfg.CreateMap<BorrowerResidence, Model.ServiceResponseModels.Rainmaker.BorrowerResidence>();
                // cfg.CreateMap<RainMaker.Entity.Models.BorrowerSupportPayment, Rainmaker.Model.ServiceResponseModels.LoanApplication.BorrowerSupportPayment>();
                // cfg.CreateMap<RainMaker.Entity.Models.Branch, Rainmaker.Model.ServiceResponseModels.LoanApplication.Branch>();
                // cfg.CreateMap<RainMaker.Entity.Models.BranchEmail, Rainmaker.Model.ServiceResponseModels.LoanApplication.BranchEmail>();
                // cfg.CreateMap<RainMaker.Entity.Models.BranchPhone, Rainmaker.Model.ServiceResponseModels.LoanApplication.BranchPhone>();
                // cfg.CreateMap<RainMaker.Entity.Models.BranchPhoneBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.BranchPhoneBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.BreachedPassword, Rainmaker.Model.ServiceResponseModels.LoanApplication.BreachedPassword>();
                cfg.CreateMap<BusinessUnit, Model.ServiceResponseModels.Rainmaker.BusinessUnit>();
                // cfg.CreateMap<RainMaker.Entity.Models.BusinessUnitEmail, Rainmaker.Model.ServiceResponseModels.LoanApplication.BusinessUnitEmail>();
                // cfg.CreateMap<RainMaker.Entity.Models.BusinessUnitPhone, Rainmaker.Model.ServiceResponseModels.LoanApplication.BusinessUnitPhone>();
                // cfg.CreateMap<RainMaker.Entity.Models.BusinessUnitPhoneBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.BusinessUnitPhoneBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.Campaign, Rainmaker.Model.ServiceResponseModels.LoanApplication.Campaign>();
                // cfg.CreateMap<RainMaker.Entity.Models.CampaignActivityBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.CampaignActivityBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.CampaignQueue, Rainmaker.Model.ServiceResponseModels.LoanApplication.CampaignQueue>();
                // cfg.CreateMap<RainMaker.Entity.Models.CampaignTrigger, Rainmaker.Model.ServiceResponseModels.LoanApplication.CampaignTrigger>();
                // cfg.CreateMap<RainMaker.Entity.Models.CampaignTriggerBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.CampaignTriggerBinder>();
                cfg.CreateMap<City, Model.ServiceResponseModels.Rainmaker.City>();
                // cfg.CreateMap<RainMaker.Entity.Models.CmsPage, Rainmaker.Model.ServiceResponseModels.LoanApplication.CmsPage>();
                cfg.CreateMap<CompanyPhoneInfo, Model.ServiceResponseModels.Rainmaker.CompanyPhoneInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.ConsentType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ConsentType>();
                cfg.CreateMap<Contact, Model.ServiceResponseModels.Rainmaker.Contact>();
                // cfg.CreateMap<RainMaker.Entity.Models.ContactAddress, Rainmaker.Model.ServiceResponseModels.LoanApplication.ContactAddress>();
                // cfg.CreateMap<RainMaker.Entity.Models.ContactEmailInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.ContactEmailInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.ContactInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.ContactInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.ContactPhoneInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.ContactPhoneInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.ContactSearchView, Rainmaker.Model.ServiceResponseModels.LoanApplication.ContactSearchView>();
                cfg.CreateMap<Country, Model.ServiceResponseModels.Rainmaker.Country>();
                cfg.CreateMap<County, Model.ServiceResponseModels.Rainmaker.County>();
                // cfg.CreateMap<RainMaker.Entity.Models.CountyType, Rainmaker.Model.ServiceResponseModels.LoanApplication.CountyType>();
                // cfg.CreateMap<RainMaker.Entity.Models.CreditScore, Rainmaker.Model.ServiceResponseModels.LoanApplication.CreditScore>();
                // cfg.CreateMap<RainMaker.Entity.Models.CurrentRate, Rainmaker.Model.ServiceResponseModels.LoanApplication.CurrentRate>();
                // cfg.CreateMap<RainMaker.Entity.Models.CurrentRateView, Rainmaker.Model.ServiceResponseModels.LoanApplication.CurrentRateView>();
                // cfg.CreateMap<RainMaker.Entity.Models.CusSubscriptionBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.CusSubscriptionBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.Customer, Rainmaker.Model.ServiceResponseModels.LoanApplication.Customer>();
                // cfg.CreateMap<RainMaker.Entity.Models.CustomerInfoView, Rainmaker.Model.ServiceResponseModels.LoanApplication.CustomerInfoView>();
                // cfg.CreateMap<RainMaker.Entity.Models.CustomerType, Rainmaker.Model.ServiceResponseModels.LoanApplication.CustomerType>();
                // cfg.CreateMap<RainMaker.Entity.Models.CustomerTypeBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.CustomerTypeBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.DebtToIncomeRatio, Rainmaker.Model.ServiceResponseModels.LoanApplication.DebtToIncomeRatio>();
                // cfg.CreateMap<RainMaker.Entity.Models.DefaultLoanParameter, Rainmaker.Model.ServiceResponseModels.LoanApplication.DefaultLoanParameter>();
                cfg.CreateMap<DemographicMedium, Model.ServiceResponseModels.Rainmaker.DemographicMedium>();
                // cfg.CreateMap<RainMaker.Entity.Models.DenormOpportunityContact, Rainmaker.Model.ServiceResponseModels.LoanApplication.DenormOpportunityContact>();
                // cfg.CreateMap<RainMaker.Entity.Models.Department, Rainmaker.Model.ServiceResponseModels.LoanApplication.Department>();
                // cfg.CreateMap<RainMaker.Entity.Models.EducationFormat, Rainmaker.Model.ServiceResponseModels.LoanApplication.EducationFormat>();
                cfg.CreateMap<EmailAccount, Model.ServiceResponseModels.Rainmaker.EmailAccount>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailAttachmentsLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailAttachmentsLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailLinkTracking, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailLinkTracking>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailLogBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailLogBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailLogTrackingView, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailLogTrackingView>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailTracking, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailTracking>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmailVerification, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmailVerification>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmpAssignmentRuleBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmpAssignmentRuleBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmpDepartmentBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmpDepartmentBinder>();
                cfg.CreateMap<Employee, Model.ServiceResponseModels.Rainmaker.Employee>();
                cfg.CreateMap<EmployeeBusinessUnitEmail, Model.ServiceResponseModels.Rainmaker.EmployeeBusinessUnitEmail>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmployeeCsrLoBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmployeeCsrLoBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.EmployeeLicense, Rainmaker.Model.ServiceResponseModels.LoanApplication.EmployeeLicense>();
                cfg.CreateMap<EmployeePhoneBinder, Model.ServiceResponseModels.Rainmaker.EmployeePhoneBinder>();
                cfg.CreateMap<EmploymentInfo, Model.ServiceResponseModels.Rainmaker.EmploymentInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.EntityType, Rainmaker.Model.ServiceResponseModels.LoanApplication.EntityType>();
                // cfg.CreateMap<RainMaker.Entity.Models.EscrowEntityType, Rainmaker.Model.ServiceResponseModels.LoanApplication.EscrowEntityType>();
                cfg.CreateMap<Ethnicity, Model.ServiceResponseModels.Rainmaker.Ethnicity>();
                cfg.CreateMap<EthnicityDetail, Model.ServiceResponseModels.Rainmaker.EthnicityDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.FamilyRelationType, Rainmaker.Model.ServiceResponseModels.LoanApplication.FamilyRelationType>();
                // cfg.CreateMap<RainMaker.Entity.Models.Fee, Rainmaker.Model.ServiceResponseModels.LoanApplication.Fee>();
                // cfg.CreateMap<RainMaker.Entity.Models.FeeBlock, Rainmaker.Model.ServiceResponseModels.LoanApplication.FeeBlock>();
                // cfg.CreateMap<RainMaker.Entity.Models.FeeCategory, Rainmaker.Model.ServiceResponseModels.LoanApplication.FeeCategory>();
                // cfg.CreateMap<RainMaker.Entity.Models.FeeDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.FeeDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.FeeDetailPaidBy, Rainmaker.Model.ServiceResponseModels.LoanApplication.FeeDetailPaidBy>();
                // cfg.CreateMap<RainMaker.Entity.Models.FeeType, Rainmaker.Model.ServiceResponseModels.LoanApplication.FeeType>();
                // cfg.CreateMap<RainMaker.Entity.Models.FileAttachment, Rainmaker.Model.ServiceResponseModels.LoanApplication.FileAttachment>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUp, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUp>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpActivity, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpActivity>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpActivityBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpActivityBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpActivityPurposeBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpActivityPurposeBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpPriority, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpPriority>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpPurpose, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpPurpose>();
                // cfg.CreateMap<RainMaker.Entity.Models.FollowUpReminderVia, Rainmaker.Model.ServiceResponseModels.LoanApplication.FollowUpReminderVia>();
                // cfg.CreateMap<RainMaker.Entity.Models.Formula, Rainmaker.Model.ServiceResponseModels.LoanApplication.Formula>();
                cfg.CreateMap<Gender, Model.ServiceResponseModels.Rainmaker.Gender>();
                // cfg.CreateMap<RainMaker.Entity.Models.GenericAttribute, Rainmaker.Model.ServiceResponseModels.LoanApplication.GenericAttribute>();
                // cfg.CreateMap<RainMaker.Entity.Models.GiftSource, Rainmaker.Model.ServiceResponseModels.LoanApplication.GiftSource>();
                // cfg.CreateMap<RainMaker.Entity.Models.HolidayType, Rainmaker.Model.ServiceResponseModels.LoanApplication.HolidayType>();
                cfg.CreateMap<IncomeType, Model.ServiceResponseModels.Rainmaker.IncomeType>();
                // cfg.CreateMap<RainMaker.Entity.Models.InformationMedium, Rainmaker.Model.ServiceResponseModels.LoanApplication.InformationMedium>();
                // cfg.CreateMap<RainMaker.Entity.Models.InitialContact, Rainmaker.Model.ServiceResponseModels.LoanApplication.InitialContact>();
                // cfg.CreateMap<RainMaker.Entity.Models.Investor, Rainmaker.Model.ServiceResponseModels.LoanApplication.Investor>();
                // cfg.CreateMap<RainMaker.Entity.Models.InvestorProduct, Rainmaker.Model.ServiceResponseModels.LoanApplication.InvestorProduct>();
                cfg.CreateMap<JobType, Model.ServiceResponseModels.Rainmaker.JobType>();
                // cfg.CreateMap<RainMaker.Entity.Models.Language, Rainmaker.Model.ServiceResponseModels.LoanApplication.Language>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGenAnswerSelection, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGenAnswerSelection>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGenAnswerSelectionView, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGenAnswerSelectionView>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGenQuestionGroup, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGenQuestionGroup>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGenQuestionTree, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGenQuestionTree>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGridView, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGridView>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadGroup, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadGroup>();
                cfg.CreateMap<LeadSource, Model.ServiceResponseModels.Rainmaker.LeadSource>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadSourceDefaultProduct, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadSourceDefaultProduct>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadSourceType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadSourceType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LeadType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LeadType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeFee, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeFee>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeLead, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeLead>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeLoanRequestPurpose, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeLoanRequestPurpose>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeOption, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeOption>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeQuote, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeQuote>();
                // cfg.CreateMap<RainMaker.Entity.Models.LendingTreeScore, Rainmaker.Model.ServiceResponseModels.LoanApplication.LendingTreeScore>();
                cfg.CreateMap<LiabilityType, Model.ServiceResponseModels.Rainmaker.LiabilityType>();
                cfg.CreateMap<LoanApplication, Model.ServiceResponseModels.Rainmaker.LoanApplication>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanApplicationFee, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanApplicationFee>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanApplicationView, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanApplicationView>();
                cfg.CreateMap<LoanContact, Model.ServiceResponseModels.Rainmaker.LoanContact>();
                cfg.CreateMap<LoanContactEthnicityBinder, Model.ServiceResponseModels.Rainmaker.LoanContactEthnicityBinder>();
                cfg.CreateMap<LoanContactRaceBinder, Model.ServiceResponseModels.Rainmaker.LoanContactRaceBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocument, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocument>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocumentPipeLine, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocumentPipeLine>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocumentPipeLineView, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocumentPipeLineView>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocumentStatusList, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocumentStatusList>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocumentSubType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocumentSubType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanDocumentType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanDocumentType>();
                cfg.CreateMap<LoanGoal, Model.ServiceResponseModels.Rainmaker.LoanGoal>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanIndexType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanIndexType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanLockPeriod, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanLockPeriod>();
                cfg.CreateMap<LoanPurpose, Model.ServiceResponseModels.Rainmaker.LoanPurpose>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanPurposeProgram, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanPurposeProgram>();
                cfg.CreateMap<LoanRequest, Model.ServiceResponseModels.Rainmaker.LoanRequest>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestMergeLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestMergeLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestMessageBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestMessageBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestProduct, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestProduct>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestProductClass, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestProductClass>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestProductType, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestProductType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanRequestQuestionBinding, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanRequestQuestionBinding>();
                // cfg.CreateMap<RainMaker.Entity.Models.LoanToValue, Rainmaker.Model.ServiceResponseModels.LoanApplication.LoanToValue>();
                cfg.CreateMap<LoanType, Model.ServiceResponseModels.Rainmaker.LoanType>();
                // cfg.CreateMap<RainMaker.Entity.Models.LocaleStringResource, Rainmaker.Model.ServiceResponseModels.LoanApplication.LocaleStringResource>();
                // cfg.CreateMap<RainMaker.Entity.Models.LockDaysOnRule, Rainmaker.Model.ServiceResponseModels.LoanApplication.LockDaysOnRule>();
                // cfg.CreateMap<RainMaker.Entity.Models.LockStatusCause, Rainmaker.Model.ServiceResponseModels.LoanApplication.LockStatusCause>();
                // cfg.CreateMap<RainMaker.Entity.Models.LockStatusList, Rainmaker.Model.ServiceResponseModels.LoanApplication.LockStatusList>();
                // cfg.CreateMap<RainMaker.Entity.Models.LogItem, Rainmaker.Model.ServiceResponseModels.LoanApplication.LogItem>();
                cfg.CreateMap<MaritalStatusList, Model.ServiceResponseModels.Rainmaker.MaritalStatusList>();
                cfg.CreateMap<MaritalStatusType, Model.ServiceResponseModels.Rainmaker.MaritalStatusType>();
                // cfg.CreateMap<RainMaker.Entity.Models.MarksmanLead, Rainmaker.Model.ServiceResponseModels.LoanApplication.MarksmanLead>();
                // cfg.CreateMap<RainMaker.Entity.Models.MarksmanLeadDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.MarksmanLeadDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.MarksmanQuote, Rainmaker.Model.ServiceResponseModels.LoanApplication.MarksmanQuote>();
                // cfg.CreateMap<RainMaker.Entity.Models.MbsRate, Rainmaker.Model.ServiceResponseModels.LoanApplication.MbsRate>();
                // cfg.CreateMap<RainMaker.Entity.Models.MbsRateArchive, Rainmaker.Model.ServiceResponseModels.LoanApplication.MbsRateArchive>();
                // cfg.CreateMap<RainMaker.Entity.Models.MbsSecurity, Rainmaker.Model.ServiceResponseModels.LoanApplication.MbsSecurity>();
                // cfg.CreateMap<RainMaker.Entity.Models.MessageOnRule, Rainmaker.Model.ServiceResponseModels.LoanApplication.MessageOnRule>();
                // cfg.CreateMap<RainMaker.Entity.Models.MessageTemplate, Rainmaker.Model.ServiceResponseModels.LoanApplication.MessageTemplate>();
                // cfg.CreateMap<RainMaker.Entity.Models.MilitaryAffiliation, Rainmaker.Model.ServiceResponseModels.LoanApplication.MilitaryAffiliation>();
                // cfg.CreateMap<RainMaker.Entity.Models.MilitaryBranch, Rainmaker.Model.ServiceResponseModels.LoanApplication.MilitaryBranch>();
                // cfg.CreateMap<RainMaker.Entity.Models.MilitaryStatusList, Rainmaker.Model.ServiceResponseModels.LoanApplication.MilitaryStatusList>();
                // cfg.CreateMap<RainMaker.Entity.Models.MortgageEducation, Rainmaker.Model.ServiceResponseModels.LoanApplication.MortgageEducation>();
                // cfg.CreateMap<RainMaker.Entity.Models.MortgageEducationType, Rainmaker.Model.ServiceResponseModels.LoanApplication.MortgageEducationType>();
                cfg.CreateMap<MortgageOnProperty, Model.ServiceResponseModels.Rainmaker.MortgageOnProperty>();
                // cfg.CreateMap<RainMaker.Entity.Models.Note, Rainmaker.Model.ServiceResponseModels.LoanApplication.Note>();
                // cfg.CreateMap<RainMaker.Entity.Models.NoteDepartmentBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.NoteDepartmentBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.NoteDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.NoteDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.NoteSubject, Rainmaker.Model.ServiceResponseModels.LoanApplication.NoteSubject>();
                // cfg.CreateMap<RainMaker.Entity.Models.NoteTopic, Rainmaker.Model.ServiceResponseModels.LoanApplication.NoteTopic>();
                // cfg.CreateMap<RainMaker.Entity.Models.Notification, Rainmaker.Model.ServiceResponseModels.LoanApplication.Notification>();
                // cfg.CreateMap<RainMaker.Entity.Models.NotificationChange, Rainmaker.Model.ServiceResponseModels.LoanApplication.NotificationChange>();
                // cfg.CreateMap<RainMaker.Entity.Models.NotificationObject, Rainmaker.Model.ServiceResponseModels.LoanApplication.NotificationObject>();
                // cfg.CreateMap<RainMaker.Entity.Models.NotificationObject, Rainmaker.Model.ServiceResponseModels.LoanApplication.NotificationObject>();
                // cfg.CreateMap<RainMaker.Entity.Models.NotificationTo, Rainmaker.Model.ServiceResponseModels.LoanApplication.NotificationTo>();
                // cfg.CreateMap<RainMaker.Entity.Models.ObjectType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ObjectType>();
                // cfg.CreateMap<RainMaker.Entity.Models.OfficeHoliday, Rainmaker.Model.ServiceResponseModels.LoanApplication.OfficeHoliday>();
                // cfg.CreateMap<RainMaker.Entity.Models.OfficeMetroBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.OfficeMetroBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.OppAssignLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.OppAssignLog>();
                cfg.CreateMap<Opportunity, Model.ServiceResponseModels.Rainmaker.Opportunity>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityDesireRate, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityDesireRate>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityFee, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityFee>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityFeeDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityFeeDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityFeeDetailPaidBy, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityFeeDetailPaidBy>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityFeePaidBy, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityFeePaidBy>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityLeadBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityLeadBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityLockStatusLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityLockStatusLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityPropertyTax, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityPropertyTax>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityStatusLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityStatusLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.OpportunityTaxOn, Rainmaker.Model.ServiceResponseModels.LoanApplication.OpportunityTaxOn>();
                cfg.CreateMap<OtherEmploymentIncome, Model.ServiceResponseModels.Rainmaker.OtherEmploymentIncome>();
                cfg.CreateMap<OtherEmploymentIncomeHistory, Model.ServiceResponseModels.Rainmaker.OtherEmploymentIncomeHistory>();
                cfg.CreateMap<OtherEmploymentIncomeType, Model.ServiceResponseModels.Rainmaker.OtherEmploymentIncomeType>();
                cfg.CreateMap<OtherIncome, Model.ServiceResponseModels.Rainmaker.OtherIncome>();
                // cfg.CreateMap<RainMaker.Entity.Models.OtpTracing, Rainmaker.Model.ServiceResponseModels.LoanApplication.OtpTracing>();
                // cfg.CreateMap<RainMaker.Entity.Models.OwnerShipInterest, Rainmaker.Model.ServiceResponseModels.LoanApplication.OwnerShipInterest>();
                // cfg.CreateMap<RainMaker.Entity.Models.OwnershipType, Rainmaker.Model.ServiceResponseModels.LoanApplication.OwnershipType>();
                // cfg.CreateMap<RainMaker.Entity.Models.OwnType, Rainmaker.Model.ServiceResponseModels.LoanApplication.OwnType>();
                // cfg.CreateMap<RainMaker.Entity.Models.PaidBy, Rainmaker.Model.ServiceResponseModels.LoanApplication.PaidBy>();
                // cfg.CreateMap<RainMaker.Entity.Models.PasswordPolicy, Rainmaker.Model.ServiceResponseModels.LoanApplication.PasswordPolicy>();
                // cfg.CreateMap<RainMaker.Entity.Models.PaymentOn, Rainmaker.Model.ServiceResponseModels.LoanApplication.PaymentOn>();
                // cfg.CreateMap<RainMaker.Entity.Models.PmiCompany, Rainmaker.Model.ServiceResponseModels.LoanApplication.PmiCompany>();
                // cfg.CreateMap<RainMaker.Entity.Models.Position, Rainmaker.Model.ServiceResponseModels.LoanApplication.Position>();
                // cfg.CreateMap<RainMaker.Entity.Models.PrepayPenalty, Rainmaker.Model.ServiceResponseModels.LoanApplication.PrepayPenalty>();
                // cfg.CreateMap<RainMaker.Entity.Models.Product, Rainmaker.Model.ServiceResponseModels.LoanApplication.Product>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductAd, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductAd>();
                //cfg.CreateMap<RainMaker.Entity.Models.ProductAmortizationType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductAmortizationType>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductBestEx, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductBestEx>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductCatalog, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductCatalog>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductClass, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductClass>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductFamily, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductFamily>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductQualifier, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductQualifier>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductTemplatekey, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductTemplatekey>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProductType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProductType>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProfitTable, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProfitTable>();
                // cfg.CreateMap<RainMaker.Entity.Models.ProjectType, Rainmaker.Model.ServiceResponseModels.LoanApplication.ProjectType>();
                // cfg.CreateMap<RainMaker.Entity.Models.PromotionalProgram, Rainmaker.Model.ServiceResponseModels.LoanApplication.PromotionalProgram>();
                cfg.CreateMap<PropertyInfo, Model.ServiceResponseModels.Rainmaker.PropertyInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.PropertyTax, Rainmaker.Model.ServiceResponseModels.LoanApplication.PropertyTax>();
                cfg.CreateMap<PropertyTaxEscrow, Model.ServiceResponseModels.Rainmaker.PropertyTaxEscrow>();
                cfg.CreateMap<PropertyType, Model.ServiceResponseModels.Rainmaker.PropertyType>();
                cfg.CreateMap<PropertyUsage, Model.ServiceResponseModels.Rainmaker.PropertyUsage>();
                // cfg.CreateMap<RainMaker.Entity.Models.QtPhoneInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.QtPhoneInfo>();
                cfg.CreateMap<Question, Model.ServiceResponseModels.Rainmaker.Question>();
                // cfg.CreateMap<RainMaker.Entity.Models.QuestionGroup, Rainmaker.Model.ServiceResponseModels.LoanApplication.QuestionGroup>();
                // cfg.CreateMap<RainMaker.Entity.Models.QuestionOption, Rainmaker.Model.ServiceResponseModels.LoanApplication.QuestionOption>();
                // cfg.CreateMap<RainMaker.Entity.Models.QuestionPurposeBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.QuestionPurposeBinder>();
                cfg.CreateMap<QuestionResponse, Model.ServiceResponseModels.Rainmaker.QuestionResponse>();
                // cfg.CreateMap<RainMaker.Entity.Models.QuestionSection, Rainmaker.Model.ServiceResponseModels.LoanApplication.QuestionSection>();
                // cfg.CreateMap<RainMaker.Entity.Models.QuestionType, Rainmaker.Model.ServiceResponseModels.LoanApplication.QuestionType>();
                cfg.CreateMap<Race, Model.ServiceResponseModels.Rainmaker.Race>();
                cfg.CreateMap<RaceDetail, Model.ServiceResponseModels.Rainmaker.RaceDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.RangeSet, Rainmaker.Model.ServiceResponseModels.LoanApplication.RangeSet>();
                // cfg.CreateMap<RainMaker.Entity.Models.RangeSetDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.RangeSetDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.RateArchive, Rainmaker.Model.ServiceResponseModels.LoanApplication.RateArchive>();
                // cfg.CreateMap<RainMaker.Entity.Models.RateServiceParameter, Rainmaker.Model.ServiceResponseModels.LoanApplication.RateServiceParameter>();
                // cfg.CreateMap<RainMaker.Entity.Models.RateWidget, Rainmaker.Model.ServiceResponseModels.LoanApplication.RateWidget>();
                // cfg.CreateMap<RainMaker.Entity.Models.Region, Rainmaker.Model.ServiceResponseModels.LoanApplication.Region>();
                cfg.CreateMap<ResidencyState, Model.ServiceResponseModels.Rainmaker.ResidencyState>();
                cfg.CreateMap<ResidencyType, Model.ServiceResponseModels.Rainmaker.ResidencyType>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewComment, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewComment>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewContact, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewContact>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewPosted, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewPosted>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewProperty, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewProperty>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewSite, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewSite>();
                // cfg.CreateMap<RainMaker.Entity.Models.ReviewSiteAccount, Rainmaker.Model.ServiceResponseModels.LoanApplication.ReviewSiteAccount>();
                // cfg.CreateMap<RainMaker.Entity.Models.Rule, Rainmaker.Model.ServiceResponseModels.LoanApplication.Rule>();
                // cfg.CreateMap<RainMaker.Entity.Models.RuleMessage, Rainmaker.Model.ServiceResponseModels.LoanApplication.RuleMessage>();
                // cfg.CreateMap<RainMaker.Entity.Models.ScheduleActivity, Rainmaker.Model.ServiceResponseModels.LoanApplication.ScheduleActivity>();
                // cfg.CreateMap<RainMaker.Entity.Models.ScheduleActivityLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.ScheduleActivityLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.Scheduler, Rainmaker.Model.ServiceResponseModels.LoanApplication.Scheduler>();
                // cfg.CreateMap<RainMaker.Entity.Models.SecondLien, Rainmaker.Model.ServiceResponseModels.LoanApplication.SecondLien>();
                // cfg.CreateMap<RainMaker.Entity.Models.SecondLienType, Rainmaker.Model.ServiceResponseModels.LoanApplication.SecondLienType>();
                // cfg.CreateMap<RainMaker.Entity.Models.ServicesSetting, Rainmaker.Model.ServiceResponseModels.LoanApplication.ServicesSetting>();
                // cfg.CreateMap<RainMaker.Entity.Models.SessionLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.SessionLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.SessionLogDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.SessionLogDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.Setting, Rainmaker.Model.ServiceResponseModels.LoanApplication.Setting>();
                // cfg.CreateMap<RainMaker.Entity.Models.SettingGroup, Rainmaker.Model.ServiceResponseModels.LoanApplication.SettingGroup>();
                // cfg.CreateMap<RainMaker.Entity.Models.SettingGroupBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.SettingGroupBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.SetupTable, Rainmaker.Model.ServiceResponseModels.LoanApplication.SetupTable>();
                // cfg.CreateMap<RainMaker.Entity.Models.Sitemap, Rainmaker.Model.ServiceResponseModels.LoanApplication.Sitemap>();
                cfg.CreateMap<State, Model.ServiceResponseModels.Rainmaker.State>();
                // cfg.CreateMap<RainMaker.Entity.Models.StateCountyCity, Rainmaker.Model.ServiceResponseModels.LoanApplication.StateCountyCity>();
                // cfg.CreateMap<RainMaker.Entity.Models.StatusCause, Rainmaker.Model.ServiceResponseModels.LoanApplication.StatusCause>();
                cfg.CreateMap<StatusList, Model.ServiceResponseModels.Rainmaker.StatusList>();
                // cfg.CreateMap<RainMaker.Entity.Models.Subordinate, Rainmaker.Model.ServiceResponseModels.LoanApplication.Subordinate>();
                // cfg.CreateMap<RainMaker.Entity.Models.Subscription, Rainmaker.Model.ServiceResponseModels.LoanApplication.Subscription>();
                // cfg.CreateMap<RainMaker.Entity.Models.SubscriptionGroup, Rainmaker.Model.ServiceResponseModels.LoanApplication.SubscriptionGroup>();
                // cfg.CreateMap<RainMaker.Entity.Models.SubscriptionSection, Rainmaker.Model.ServiceResponseModels.LoanApplication.SubscriptionSection>();
                // cfg.CreateMap<RainMaker.Entity.Models.SupportPaymentType, Rainmaker.Model.ServiceResponseModels.LoanApplication.SupportPaymentType>();
                // cfg.CreateMap<RainMaker.Entity.Models.SystemEvent, Rainmaker.Model.ServiceResponseModels.LoanApplication.SystemEvent>();
                // cfg.CreateMap<RainMaker.Entity.Models.SystemEventLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.SystemEventLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.TaxCityBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.TaxCityBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.TaxCountyBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.TaxCountyBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.Team, Rainmaker.Model.ServiceResponseModels.LoanApplication.Team>();
                // cfg.CreateMap<RainMaker.Entity.Models.TeamMember, Rainmaker.Model.ServiceResponseModels.LoanApplication.TeamMember>();
                // cfg.CreateMap<RainMaker.Entity.Models.ThirdPartyCode, Rainmaker.Model.ServiceResponseModels.LoanApplication.ThirdPartyCode>();
                // cfg.CreateMap<RainMaker.Entity.Models.ThirdPartyLead, Rainmaker.Model.ServiceResponseModels.LoanApplication.ThirdPartyLead>();
                // cfg.CreateMap<RainMaker.Entity.Models.ThirdPartyStatusList, Rainmaker.Model.ServiceResponseModels.LoanApplication.ThirdPartyStatusList>();
                // cfg.CreateMap<RainMaker.Entity.Models.TimeZone, Rainmaker.Model.ServiceResponseModels.LoanApplication.TimeZone>();
                // cfg.CreateMap<RainMaker.Entity.Models.TitleEstate, Rainmaker.Model.ServiceResponseModels.LoanApplication.TitleEstate>();
                // cfg.CreateMap<RainMaker.Entity.Models.TitleHeldWith, Rainmaker.Model.ServiceResponseModels.LoanApplication.TitleHeldWith>();
                // cfg.CreateMap<RainMaker.Entity.Models.TitleLandTenure, Rainmaker.Model.ServiceResponseModels.LoanApplication.TitleLandTenure>();
                // cfg.CreateMap<RainMaker.Entity.Models.TitleManner, Rainmaker.Model.ServiceResponseModels.LoanApplication.TitleManner>();
                // cfg.CreateMap<RainMaker.Entity.Models.TitleTrustInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.TitleTrustInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.TransactionInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.TransactionInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.TransactionInfoBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.TransactionInfoBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.TriggerValue, Rainmaker.Model.ServiceResponseModels.LoanApplication.TriggerValue>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserAuthBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserAuthBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserGridSetting, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserGridSetting>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserInRole, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserInRole>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserPermission, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserPermission>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserPermissionRoleBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserPermissionRoleBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserPermissionType, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserPermissionType>();
                cfg.CreateMap<UserProfile, Model.ServiceResponseModels.Rainmaker.UserProfile>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserResetPasswordKey, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserResetPasswordKey>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserResetPasswordLog, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserResetPasswordLog>();
                // cfg.CreateMap<RainMaker.Entity.Models.UserRole, Rainmaker.Model.ServiceResponseModels.LoanApplication.UserRole>();
                // cfg.CreateMap<RainMaker.Entity.Models.VaDetail, Rainmaker.Model.ServiceResponseModels.LoanApplication.VaDetail>();
                // cfg.CreateMap<RainMaker.Entity.Models.VaOccupancy, Rainmaker.Model.ServiceResponseModels.LoanApplication.VaOccupancy>();
                // cfg.CreateMap<RainMaker.Entity.Models.VEmployeePhoneInfo, Rainmaker.Model.ServiceResponseModels.LoanApplication.VEmployeePhoneInfo>();
                // cfg.CreateMap<RainMaker.Entity.Models.Vendor, Rainmaker.Model.ServiceResponseModels.LoanApplication.Vendor>();
                // cfg.CreateMap<RainMaker.Entity.Models.VendorCustomerBinder, Rainmaker.Model.ServiceResponseModels.LoanApplication.VendorCustomerBinder>();
                // cfg.CreateMap<RainMaker.Entity.Models.VendorType, Rainmaker.Model.ServiceResponseModels.LoanApplication.VendorType>();
                // cfg.CreateMap<RainMaker.Entity.Models.Visitor, Rainmaker.Model.ServiceResponseModels.LoanApplication.Visitor>();
                // cfg.CreateMap<RainMaker.Entity.Models.ZillowLead, Rainmaker.Model.ServiceResponseModels.LoanApplication.ZillowLead>();
                // cfg.CreateMap<RainMaker.Entity.Models.ZipCode, Rainmaker.Model.ServiceResponseModels.LoanApplication.ZipCode>();
            });
            return config;
        }
    }
}