// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // EmailLogBinder
    
    public partial class EmailLogBinderMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<EmailLogBinder>
    {
        public void Configure(EntityTypeBuilder<EmailLogBinder> builder)
        {
            builder.ToTable("EmailLogBinder", "dbo");
            builder.HasKey(x => new { x.EmailLogId, x.ContactId });

            builder.Property(x => x.EmailLogId).HasColumnName(@"EmailLogId").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ContactId).HasColumnName(@"ContactId").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Contact).WithMany(b => b.EmailLogBinders).HasForeignKey(c => c.ContactId).OnDelete(DeleteBehavior.SetNull); // FK_EmailLogBinder_Contact
            builder.HasOne(a => a.EmailLog).WithMany(b => b.EmailLogBinders).HasForeignKey(c => c.EmailLogId).OnDelete(DeleteBehavior.SetNull); // FK_EmailLogBinder_EmailLog
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
