// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using RainMaker.Entity.Models;

    // LendingTreeLoanRequestPurpose
    
    public partial class LendingTreeLoanRequestPurposeMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<LendingTreeLoanRequestPurpose>
    {
        public void Configure(EntityTypeBuilder<LendingTreeLoanRequestPurpose> builder)
        {
            builder.ToTable("LendingTreeLoanRequestPurpose", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.LendingTreeLeadId).HasColumnName(@"LendingTreeLeadId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LoanRequestPurposeId).HasColumnName(@"LoanRequestPurposeId").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.LoanRequestPurpose).HasColumnName(@"LoanRequestPurpose").HasColumnType("nvarchar").IsRequired(false).HasMaxLength(500);

            // Foreign keys
            builder.HasOne(a => a.LendingTreeLead).WithMany(b => b.LendingTreeLoanRequestPurposes).HasForeignKey(c => c.LendingTreeLeadId).OnDelete(DeleteBehavior.SetNull); // FK_LendingTreeLoanRequestPurpose_LendingTreeLead
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
