// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // MbsRate
    
    public partial class MbsRate : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public System.DateTime UpdateOnUtc { get; set; } // UpdateOnUtc
        public int MbsSecurityId { get; set; } // MbsSecurityId
        public decimal CouponRate { get; set; } // CouponRate
        public System.DateTime SettlementMonth { get; set; } // SettlementMonth
        public decimal Price { get; set; } // Price
        public System.DateTime CreatedOnUtc { get; set; } // CreatedOnUtc
        public int EntityTypeId { get; set; } // EntityTypeId

        // Foreign keys

        /// <summary>
        /// Parent MbsSecurity pointed by [MbsRate].([MbsSecurityId]) (FK_MbsRate_MbsSecurity)
        /// </summary>
        public virtual MbsSecurity MbsSecurity { get; set; } // FK_MbsRate_MbsSecurity

        public MbsRate()
        {
            EntityTypeId = 198;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
