namespace Rainmaker.Model.ServiceResponseModels.Rainmaker
{
    public class ZillowLead
    {
        public int Id { get; set; }
        public string ZillowId { get; set; }
        public string Created { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public decimal? Price { get; set; }
        public string ReceiverLenderId { get; set; }
        public string ReceiverFirstName { get; set; }
        public string ReceiverLastName { get; set; }
        public string ReceiverEmailAddress { get; set; }
        public string ReceiverPhoneNumber { get; set; }
        public string ReceiverNmlsLicense { get; set; }
        public string SenderEmailAddress { get; set; }
        public string SenderFirstName { get; set; }
        public string SenderLastName { get; set; }
        public string SenderPhoneNumber { get; set; }
        public bool? AcceptPrepaymentPenalty { get; set; }
        public string AgentBusinessName { get; set; }
        public string AgentEmailAddress { get; set; }
        public string AgentFirstName { get; set; }
        public string AgentId { get; set; }
        public string AgentLastName { get; set; }
        public string AgentPhoneNumber { get; set; }
        public int? AnnualIncome { get; set; }
        public int? CashOut { get; set; }
        public string City { get; set; }
        public int? ClosingTimelineDays { get; set; }
        public string CoBorrowerFirstName { get; set; }
        public string CoBorrowerLastName { get; set; }
        public string CreditReportId { get; set; }
        public int? CreditReportScore { get; set; }
        public string CreditScoreRange { get; set; }
        public string CurrentBacker { get; set; }
        public int? CurrentBalance { get; set; }
        public decimal? DebtToIncomePercent { get; set; }
        public int? DownPayment { get; set; }
        public bool? FhaStreamlineEligible { get; set; }
        public bool? FirstTimeBuyer { get; set; }
        public bool? HarpEligible { get; set; }
        public bool? HasAgent { get; set; }
        public bool? HasBankruptcy { get; set; }
        public bool? HasCoBorrower { get; set; }
        public bool? HasForeclosure { get; set; }
        public bool? HasSecondMortgage { get; set; }
        public int? DetailLoanAmount { get; set; }
        public string LoanPurpose { get; set; }
        public decimal? LoanToValuePercent { get; set; }
        public string Message { get; set; }
        public int? MonthlyDebts { get; set; }
        public bool? NewConstruction { get; set; }
        public string PreApprovalLetterId { get; set; }
        public string PropertyAddress { get; set; }
        public string PropertyType { get; set; }
        public string PropertyUse { get; set; }
        public int? PropertyValue { get; set; }
        public string QuoteId { get; set; }
        public string RequestId { get; set; }
        public bool? SelfEmployed { get; set; }
        public string StateAbbreviation { get; set; }
        public string StreetAddress { get; set; }
        public int? TotalAssets { get; set; }
        public bool? WantsCashOut { get; set; }
        public bool? VaEligible { get; set; }
        public bool? VaFirstTimeUser { get; set; }
        public bool? VaHasDisability { get; set; }
        public string VeteranType { get; set; }
        public int? YearPurchased { get; set; }
        public string ZipCode { get; set; }
        public decimal? Rate { get; set; }
        public decimal? Apr { get; set; }
        public int? TermMonths { get; set; }
        public int? DueInMonths { get; set; }
        public int? InterestOnlyMonths { get; set; }
        public int? LockDays { get; set; }
        public bool? HasPrepaymentPenalty { get; set; }
        public bool? Jumbo { get; set; }
        public bool? Harp { get; set; }
        public bool? LenderPaidMortgageInsurance { get; set; }
        public decimal? AnnualMortgageInsurancePremiumPercent { get; set; }
        public int? FixedRateMonths { get; set; }
        public int? AdjustmentPeriodMonths { get; set; }
        public string Index { get; set; }
        public decimal? Margin { get; set; }
        public decimal? InitialCap { get; set; }
        public decimal? PeriodicCap { get; set; }
        public decimal? LifetimeCap { get; set; }
        public decimal? UpfrontPremiumPercent { get; set; }
        public decimal? AnnualPremiumPercent { get; set; }
        public bool? Streamline { get; set; }
        public decimal? FundingFeePercent { get; set; }
        public bool? CurrentBackerMustBeFannieMae { get; set; }
        public bool? CurrentBackerMustBeFreddieMac { get; set; }
        public int? LenderCredit { get; set; }
        public decimal? LenderCreditPercent { get; set; }
        public int? MaxAllowedLtv { get; set; }
        public string LoanQuoteZillowDetailsCreated { get; set; }
        public decimal? LoanQuoteZillowDetailsApr { get; set; }
        public int? UpfrontCost { get; set; }
        public int? MonthlyPrincipalAndInterest { get; set; }
        public int? MonthlyMortgageInsurance { get; set; }
        public decimal? Points { get; set; }
        public int? FeesRolledIntoLoanAmount { get; set; }
        public int? LoanQuoteZillowDetailsloanAmount { get; set; }
        public int? ThirdPartyId { get; set; }

        //public System.Collections.Generic.ICollection<ZillowLeadFee> ZillowLeadFees { get; set; }

        //public System.Collections.Generic.ICollection<ZillowLeadProgram> ZillowLeadPrograms { get; set; }

        public ThirdPartyLead ThirdPartyLead { get; set; }
    }
}