// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Notification.Entity.Models
{
    // DeliveryModeEnum

    public partial class DeliveryModeEnum : URF.Core.EF.Trackable.Entity
    {
        public short Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child NotificationRecepientMediums where [NotificationRecepientMedium].[DeliveryModeId] point to this entity (FK_NotificationRecepientMedium_DeliveryModeEnum)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NotificationRecepientMedium> NotificationRecepientMediums { get; set; } // NotificationRecepientMedium.FK_NotificationRecepientMedium_DeliveryModeEnum
        /// <summary>
        /// Child TenantSettings where [TenantSettings].[DeliveryModeId] point to this entity (FK_TenantDeliveryMode_DeliveryModeEnum)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TenantSetting> TenantSettings { get; set; } // TenantSettings.FK_TenantDeliveryMode_DeliveryModeEnum

        public DeliveryModeEnum()
        {
            NotificationRecepientMediums = new System.Collections.Generic.HashSet<NotificationRecepientMedium>();
            TenantSettings = new System.Collections.Generic.HashSet<TenantSetting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
