// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Notification.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // NotificationType
    
    public partial class NotificationType : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public short? DeliveryModeId { get; set; } // DeliveryModeId

        // Reverse navigation

        /// <summary>
        /// Child NotificationObjects where [NotificationObject].[NotificationTypeId] point to this entity (FK_NotificationObject_NotificationType_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NotificationObject> NotificationObjects { get; set; } // NotificationObject.FK_NotificationObject_NotificationType_Id
        /// <summary>
        /// Child NotificationTemplates where [NotificationTemplate].[NotificationTypeId] point to this entity (FK_NotificationTemplate_NotificationType_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NotificationTemplate> NotificationTemplates { get; set; } // NotificationTemplate.FK_NotificationTemplate_NotificationType_Id
        /// <summary>
        /// Child UserNotificationMediums where [UserNotificationMedium].[NotificationTypeId] point to this entity (FK_UserNotificationMedium_NotificationType_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserNotificationMedium> UserNotificationMediums { get; set; } // UserNotificationMedium.FK_UserNotificationMedium_NotificationType_Id

        // Foreign keys

        /// <summary>
        /// Parent DeliveryModeEnum pointed by [NotificationType].([DeliveryModeId]) (FK_NotificationType_DeliveryModeEnum_Id)
        /// </summary>
        public virtual DeliveryModeEnum DeliveryModeEnum { get; set; } // FK_NotificationType_DeliveryModeEnum_Id

        public NotificationType()
        {
            NotificationObjects = new System.Collections.Generic.HashSet<NotificationObject>();
            NotificationTemplates = new System.Collections.Generic.HashSet<NotificationTemplate>();
            UserNotificationMediums = new System.Collections.Generic.HashSet<UserNotificationMedium>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
