// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Notification.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // TenantNotificationMedium
    
    public partial class TenantNotificationMedium : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int TenantId { get; set; } // TenantId
        public int NotificationMediumId { get; set; } // NotificationMediumId
        public int NotificationTypeId { get; set; } // NotificationTypeId

        // Foreign keys

        /// <summary>
        /// Parent NotificationMedium pointed by [TenantNotificationMedium].([NotificationMediumId]) (FK_TenantNotificationMedium_NotificationMedium)
        /// </summary>
        public virtual NotificationMedium NotificationMedium { get; set; } // FK_TenantNotificationMedium_NotificationMedium

        /// <summary>
        /// Parent NotificationType pointed by [TenantNotificationMedium].([NotificationTypeId]) (FK_TenantNotificationMedium_NotificationType)
        /// </summary>
        public virtual NotificationType NotificationType { get; set; } // FK_TenantNotificationMedium_NotificationType

        public TenantNotificationMedium()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
