// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Data.Mapping
{
    using Identity.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // RolePermissionBinder
    
    public partial class RolePermissionBinderMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<RolePermissionBinder>
    {
        public void Configure(EntityTypeBuilder<RolePermissionBinder> builder)
        {
            builder.ToTable("RolePermissionBinder", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired();
            builder.Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Granted).HasColumnName(@"Granted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Permission).WithMany(b => b.RolePermissionBinders).HasForeignKey(c => c.PermissionId).OnDelete(DeleteBehavior.SetNull); // FK_RolePermissionBinder_Permission_Id
            builder.HasOne(a => a.Role).WithMany(b => b.RolePermissionBinders).HasForeignKey(c => c.RoleId).OnDelete(DeleteBehavior.SetNull); // FK_RolePermissionBinder_Role_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
