// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Data.Mapping
{
    using Identity.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // spt_fallback_usg
    
    public partial class SptFallbackUsgMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<SptFallbackUsg>
    {
        public void Configure(EntityTypeBuilder<SptFallbackUsg> builder)
        {
            builder.ToTable("spt_fallback_usg", "dbo");
            builder.HasKey(x => new { x.XserverName, x.XdttmIns, x.XdttmLastInsUpd, x.Dbid, x.Segmap, x.Lstart, x.Sizepg, x.Vstart });

            builder.Property(x => x.XserverName).HasColumnName(@"xserver_name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30).ValueGeneratedNever();
            builder.Property(x => x.XdttmIns).HasColumnName(@"xdttm_ins").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.XdttmLastInsUpd).HasColumnName(@"xdttm_last_ins_upd").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.XfallbackVstart).HasColumnName(@"xfallback_vstart").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Dbid).HasColumnName(@"dbid").HasColumnType("smallint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Segmap).HasColumnName(@"segmap").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Lstart).HasColumnName(@"lstart").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Sizepg).HasColumnName(@"sizepg").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Vstart).HasColumnName(@"vstart").HasColumnType("int").IsRequired().ValueGeneratedNever();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
