// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Data.Mapping
{
    using Identity.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // spt_fallback_db
    
    public partial class SptFallbackDbMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<SptFallbackDb>
    {
        public void Configure(EntityTypeBuilder<SptFallbackDb> builder)
        {
            builder.ToTable("spt_fallback_db", "dbo");
            builder.HasKey(x => new { x.XserverName, x.XdttmIns, x.XdttmLastInsUpd, x.Name, x.Dbid, x.Status, x.Version });

            builder.Property(x => x.XserverName).HasColumnName(@"xserver_name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30).ValueGeneratedNever();
            builder.Property(x => x.XdttmIns).HasColumnName(@"xdttm_ins").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.XdttmLastInsUpd).HasColumnName(@"xdttm_last_ins_upd").HasColumnType("datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.XfallbackDbid).HasColumnName(@"xfallback_dbid").HasColumnType("smallint").IsRequired(false);
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30).ValueGeneratedNever();
            builder.Property(x => x.Dbid).HasColumnName(@"dbid").HasColumnType("smallint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Status).HasColumnName(@"status").HasColumnType("smallint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Version).HasColumnName(@"version").HasColumnType("smallint").IsRequired().ValueGeneratedNever();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
