// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Identity.Data.Mapping
{
    using Identity.Entity.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;

    // UserPermissionBinder
    
    public partial class UserPermissionBinderMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<UserPermissionBinder>
    {
        public void Configure(EntityTypeBuilder<UserPermissionBinder> builder)
        {
            builder.ToTable("UserPermissionBinder", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Granted).HasColumnName(@"Granted").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Permission).WithMany(b => b.UserPermissionBinders).HasForeignKey(c => c.PermissionId).OnDelete(DeleteBehavior.SetNull); // FK_UserPermissionBinder_Permission_Id
            builder.HasOne(a => a.User).WithMany(b => b.UserPermissionBinders).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.SetNull); // FK_UserPermissionBinder_User_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
