// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Milestone.Data.Mapping
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using Milestone.Entity.Models;

    // ByteDocTypeMapping
    
    public partial class ByteDocTypeMappingMap : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<ByteDocTypeMapping>
    {
        public void Configure(EntityTypeBuilder<ByteDocTypeMapping> builder)
        {
            builder.ToTable("ByteDocTypeMapping", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.RmDocTypeName).HasColumnName(@"RmDocTypeName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.ByteDoctypeName).HasColumnName(@"ByteDoctypeName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            builder.Property(x => x.ByteDocCategoryId).HasColumnName(@"ByteDocCategoryId").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ByteDocCategoryMapping).WithMany(b => b.ByteDocTypeMappings).HasForeignKey(c => c.ByteDocCategoryId).OnDelete(DeleteBehavior.SetNull); // FK_ByteDocTypeMapping_ByteDocCategoryMapping
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
