// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // NotificationObject
    
    public partial class NotificationObject1 : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? NotificationTypeId { get; set; } // NotificationTypeId
        public int? EntityId { get; set; } // EntityId
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public bool? Active { get; set; } // Active
        public byte? Status { get; set; } // Status

        // Reverse navigation

        /// <summary>
        /// Child NotificationChanges where [NotificationChange].[NotificationObjectId] point to this entity (FK_NotificationChange_NotificationObject_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NotificationChange> NotificationChanges { get; set; } // NotificationChange.FK_NotificationChange_NotificationObject_Id

        public NotificationObject1()
        {
            NotificationChanges = new System.Collections.Generic.HashSet<NotificationChange>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
