// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // UserRole
    
    public partial class UserRole : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public string RoleName { get; set; } // RoleName (length: 256)
        public string LoweredRoleName { get; set; } // LoweredRoleName (length: 256)
        public string Description { get; set; } // Description (length: 500)
        public int DisplayOrder { get; set; } // DisplayOrder
        public bool IsActive { get; set; } // IsActive
        public bool IsSystem { get; set; } // IsSystem
        public int? ModifiedBy { get; set; } // ModifiedBy
        public System.DateTime? ModifiedOnUtc { get; set; } // ModifiedOnUtc
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOnUtc { get; set; } // CreatedOnUtc
        public string TpId { get; set; } // TpId (length: 50)
        public int EntityTypeId { get; set; } // EntityTypeId
        public bool IsDeleted { get; set; } // IsDeleted
        public bool? IsCustomerRole { get; set; } // IsCustomerRole

        // Reverse navigation

        /// <summary>
        /// Child TeamRoleLogs where [TeamRoleLog].[RoleId] point to this entity (FK_TeamRoleLog_UserRole)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TeamRoleLog> TeamRoleLogs { get; set; } // TeamRoleLog.FK_TeamRoleLog_UserRole
        /// <summary>
        /// Child UserInRoles where [UserInRole].[RoleId] point to this entity (FK_UserInRole_UserRole)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserInRole> UserInRoles { get; set; } // UserInRole.FK_UserInRole_UserRole
        /// <summary>
        /// Child UserPermissionRoleBinders where [UserPermissionRoleBinder].[RoleId] point to this entity (FK_UserPermissionRoleBinder_UserRole)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserPermissionRoleBinder> UserPermissionRoleBinders { get; set; } // UserPermissionRoleBinder.FK_UserPermissionRoleBinder_UserRole

        public UserRole()
        {
            DisplayOrder = 0;
            IsActive = true;
            IsSystem = false;
            EntityTypeId = 136;
            IsDeleted = false;
            TeamRoleLogs = new System.Collections.Generic.HashSet<TeamRoleLog>();
            UserInRoles = new System.Collections.Generic.HashSet<UserInRole>();
            UserPermissionRoleBinders = new System.Collections.Generic.HashSet<UserPermissionRoleBinder>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
