// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RainMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;

    // WorkQueueTracking
    
    public partial class WorkQueueTracking : URF.Core.EF.Trackable.Entity
    {
        public int Id { get; set; } // Id (Primary key)
        public int WorkQueueId { get; set; } // WorkQueueId
        public System.DateTime TrackingOnUtc { get; set; } // TrackingOnUtc
        public int QueueStatusId { get; set; } // QueueStatusId
        public int EntityTypeId { get; set; } // EntityTypeId

        // Foreign keys

        /// <summary>
        /// Parent WorkQueue pointed by [WorkQueueTracking].([WorkQueueId]) (FK_WorkQueueTracking_WorkQueue)
        /// </summary>
        public virtual WorkQueue WorkQueue { get; set; } // FK_WorkQueueTracking_WorkQueue

        public WorkQueueTracking()
        {
            EntityTypeId = 82;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
