namespace ByteWebConnector.API.Models
{
    public class CustomFields
    {
        public int CustomFieldsID { get; set; }
        public string Field01 { get; set; }
        public string Field02 { get; set; }
        public string Field03 { get; set; }
        public string Field04 { get; set; }
        public string Field05 { get; set; }
        public string Field06 { get; set; }
        public string Field07 { get; set; }
        public string Field08 { get; set; }
        public string Field09 { get; set; }
        public string Field10 { get; set; }
        public string Field11 { get; set; }
        public string Field12 { get; set; }
        public string Field13 { get; set; }
        public string Field14 { get; set; }
        public string Field15 { get; set; }
        public string Field16 { get; set; }
        public string Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public string Field20 { get; set; }
        public string Field21 { get; set; }
        public string Field22 { get; set; }
        public string Field23 { get; set; }
        public string Field24 { get; set; }
        public string Field25 { get; set; }
        public string Field26 { get; set; }
        public string Field27 { get; set; }
        public string Field28 { get; set; }
        public string Field29 { get; set; }
        public string Field30 { get; set; }
        public string Field31 { get; set; }
        public string Field32 { get; set; }
        public string Field33 { get; set; }
        public string Field34 { get; set; }
        public string Field35 { get; set; }
        public string Field36 { get; set; }
        public string Field37 { get; set; }
        public string Field38 { get; set; }
        public string Field39 { get; set; }
        public string Field40 { get; set; }
        public string Field41 { get; set; }
        public string Field42 { get; set; }
        public string Field43 { get; set; }
        public string Field44 { get; set; }
        public string Field45 { get; set; }
        public string Field46 { get; set; }
        public string Field47 { get; set; }
        public string Field48 { get; set; }
        public string Field49 { get; set; }
        public string Field50 { get; set; }
        public string Field51 { get; set; }
        public string Field52 { get; set; }
        public string Field53 { get; set; }
        public string Field54 { get; set; }
        public string Field55 { get; set; }
        public string Field56 { get; set; }
        public string Field57 { get; set; }
        public string Field58 { get; set; }
        public string Field59 { get; set; }
        public string Field60 { get; set; }
        public string Field61 { get; set; }
        public string Field62 { get; set; }
        public string Field63 { get; set; }
        public string Field64 { get; set; }
        public string Field65 { get; set; }
        public string Field66 { get; set; }
        public string Field67 { get; set; }
        public string Field68 { get; set; }
        public string Field69 { get; set; }
        public string Field70 { get; set; }
        public string Field71 { get; set; }
        public string Field72 { get; set; }
        public string Field73 { get; set; }
        public string Field74 { get; set; }
        public string Field75 { get; set; }
        public string Field76 { get; set; }
        public string Field77 { get; set; }
        public string Field78 { get; set; }
        public string Field79 { get; set; }
        public string Field80 { get; set; }
        public string Field81 { get; set; }
        public string Field82 { get; set; }
        public string Field83 { get; set; }
        public string Field84 { get; set; }
        public string Field85 { get; set; }
        public string Field86 { get; set; }
        public string Field87 { get; set; }
        public string Field88 { get; set; }
        public string Field89 { get; set; }
        public string Field90 { get; set; }
        public string Field91 { get; set; }
        public string Field92 { get; set; }
        public string Field93 { get; set; }
        public string Field94 { get; set; }
        public string Field95 { get; set; }
        public string Field96 { get; set; }
        public string Field97 { get; set; }
        public string Field98 { get; set; }
        public string Field99 { get; set; }
        public string Field100 { get; set; }
        public string Field101 { get; set; }
        public string Field102 { get; set; }
        public string Field103 { get; set; }
        public string Field104 { get; set; }
        public string Field105 { get; set; }
        public string Field106 { get; set; }
        public string Field107 { get; set; }
        public string Field108 { get; set; }
        public string Field109 { get; set; }
        public string Field110 { get; set; }
        public string Field111 { get; set; }
        public string Field112 { get; set; }
        public string Field113 { get; set; }
        public string Field114 { get; set; }
        public string Field115 { get; set; }
        public string Field116 { get; set; }
        public string Field117 { get; set; }
        public string Field118 { get; set; }
        public string Field119 { get; set; }
        public string Field120 { get; set; }
        public string Field121 { get; set; }
        public string Field122 { get; set; }
        public string Field123 { get; set; }
        public string Field124 { get; set; }
        public string Field125 { get; set; }
        public string Field126 { get; set; }
        public string Field127 { get; set; }
        public string Field128 { get; set; }
        public string Field129 { get; set; }
        public string Field130 { get; set; }
        public string Field131 { get; set; }
        public string Field132 { get; set; }
        public string Field133 { get; set; }
        public string Field134 { get; set; }
        public string Field135 { get; set; }
        public string Field136 { get; set; }
        public string Field137 { get; set; }
        public string Field138 { get; set; }
        public string Field139 { get; set; }
        public string Field140 { get; set; }
        public string Field141 { get; set; }
        public string Field142 { get; set; }
        public string Field143 { get; set; }
        public string Field144 { get; set; }
        public string Field145 { get; set; }
        public string Field146 { get; set; }
        public string Field147 { get; set; }
        public string Field148 { get; set; }
        public string Field149 { get; set; }
        public string Field150 { get; set; }
        public string Field151 { get; set; }
        public string Field152 { get; set; }
        public string Field153 { get; set; }
        public string Field154 { get; set; }
        public string Field155 { get; set; }
        public string Field156 { get; set; }
        public string Field157 { get; set; }
        public string Field158 { get; set; }
        public string Field159 { get; set; }
        public string Field160 { get; set; }
        public string Field161 { get; set; }
        public string Field162 { get; set; }
        public string Field163 { get; set; }
        public string Field164 { get; set; }
        public string Field165 { get; set; }
        public string Field166 { get; set; }
        public string Field167 { get; set; }
        public string Field168 { get; set; }
        public string Field169 { get; set; }
        public string Field170 { get; set; }
        public string Field171 { get; set; }
        public string Field172 { get; set; }
        public string Field173 { get; set; }
        public string Field174 { get; set; }
        public string Field175 { get; set; }
        public string Field176 { get; set; }
        public string Field177 { get; set; }
        public string Field178 { get; set; }
        public string Field179 { get; set; }
        public string Field180 { get; set; }
        public string Field181 { get; set; }
        public string Field182 { get; set; }
        public string Field183 { get; set; }
        public string Field184 { get; set; }
        public string Field185 { get; set; }
        public string Field186 { get; set; }
        public string Field187 { get; set; }
        public string Field188 { get; set; }
        public string Field189 { get; set; }
        public string Field190 { get; set; }
        public string Field191 { get; set; }
        public string Field192 { get; set; }
        public string Field193 { get; set; }
        public string Field194 { get; set; }
        public string Field195 { get; set; }
        public string Field196 { get; set; }
        public string Field197 { get; set; }
        public string Field198 { get; set; }
        public string Field199 { get; set; }
        public string Field200 { get; set; }
        public string Field201 { get; set; }
        public string Field202 { get; set; }
        public string Field203 { get; set; }
        public string Field204 { get; set; }
        public string Field205 { get; set; }
        public string Field206 { get; set; }
        public string Field207 { get; set; }
        public string Field208 { get; set; }
        public string Field209 { get; set; }
        public string Field210 { get; set; }
        public string Field211 { get; set; }
        public string Field212 { get; set; }
        public string Field213 { get; set; }
        public string Field214 { get; set; }
        public string Field215 { get; set; }
        public string Field216 { get; set; }
        public string Field217 { get; set; }
        public string Field218 { get; set; }
        public string Field219 { get; set; }
        public string Field220 { get; set; }
        public string Field221 { get; set; }
        public string Field222 { get; set; }
        public string Field223 { get; set; }
        public string Field224 { get; set; }
        public string Field225 { get; set; }
        public string Field226 { get; set; }
        public string Field227 { get; set; }
        public string Field228 { get; set; }
        public string Field229 { get; set; }
        public string Field230 { get; set; }
        public string Field231 { get; set; }
        public string Field232 { get; set; }
        public string Field233 { get; set; }
        public string Field234 { get; set; }
        public string Field235 { get; set; }
        public string Field236 { get; set; }
        public string Field237 { get; set; }
        public string Field238 { get; set; }
        public string Field239 { get; set; }
        public string Field240 { get; set; }
        public string Field241 { get; set; }
        public string Field242 { get; set; }
        public string Field243 { get; set; }
        public string Field244 { get; set; }
        public string Field245 { get; set; }
        public string Field246 { get; set; }
        public string Field247 { get; set; }
        public string Field248 { get; set; }
        public string Field249 { get; set; }
        public string Field250 { get; set; }
        public string Field251 { get; set; }
        public string Field252 { get; set; }
        public string Field253 { get; set; }
        public string Field254 { get; set; }
        public string Field255 { get; set; }
        public string Field256 { get; set; }
        public string Field257 { get; set; }
        public string Field258 { get; set; }
        public string Field259 { get; set; }
        public string Field260 { get; set; }
        public string Field261 { get; set; }
        public string Field262 { get; set; }
        public string Field263 { get; set; }
        public string Field264 { get; set; }
        public string Field265 { get; set; }
        public string Field266 { get; set; }
        public string Field267 { get; set; }
        public string Field268 { get; set; }
        public string Field269 { get; set; }
        public string Field270 { get; set; }
        public string Field271 { get; set; }
        public string Field272 { get; set; }
        public string Field273 { get; set; }
        public string Field274 { get; set; }
        public string Field275 { get; set; }
        public string Field276 { get; set; }
        public string Field277 { get; set; }
        public string Field278 { get; set; }
        public string Field279 { get; set; }
        public string Field280 { get; set; }
        public string Field281 { get; set; }
        public string Field282 { get; set; }
        public string Field283 { get; set; }
        public string Field284 { get; set; }
        public string Field285 { get; set; }
        public string Field286 { get; set; }
        public string Field287 { get; set; }
        public string Field288 { get; set; }
        public string Field289 { get; set; }
        public string Field290 { get; set; }
        public string Field291 { get; set; }
        public string Field292 { get; set; }
        public string Field293 { get; set; }
        public string Field294 { get; set; }
        public string Field295 { get; set; }
        public string Field296 { get; set; }
        public string Field297 { get; set; }
        public string Field298 { get; set; }
        public string Field299 { get; set; }
        public string Field300 { get; set; }
        public string Field301 { get; set; }
        public string Field302 { get; set; }
        public string Field303 { get; set; }
        public string Field304 { get; set; }
        public string Field305 { get; set; }
        public string Field306 { get; set; }
        public string Field307 { get; set; }
        public string Field308 { get; set; }
        public string Field309 { get; set; }
        public string Field310 { get; set; }
        public string Field311 { get; set; }
        public string Field312 { get; set; }
        public string Field313 { get; set; }
        public string Field314 { get; set; }
        public string Field315 { get; set; }
        public string Field316 { get; set; }
        public string Field317 { get; set; }
        public string Field318 { get; set; }
        public string Field319 { get; set; }
        public string Field320 { get; set; }
        public string Field321 { get; set; }
        public string Field322 { get; set; }
        public string Field323 { get; set; }
        public string Field324 { get; set; }
        public string Field325 { get; set; }
        public string Field326 { get; set; }
        public string Field327 { get; set; }
        public string Field328 { get; set; }
        public string Field329 { get; set; }
        public string Field330 { get; set; }
        public string Field331 { get; set; }
        public string Field332 { get; set; }
        public string Field333 { get; set; }
        public string Field334 { get; set; }
        public string Field335 { get; set; }
        public string Field336 { get; set; }
        public string Field337 { get; set; }
        public string Field338 { get; set; }
        public string Field339 { get; set; }
        public string Field340 { get; set; }
        public string Field341 { get; set; }
        public string Field342 { get; set; }
        public string Field343 { get; set; }
        public string Field344 { get; set; }
        public string Field345 { get; set; }
        public string Field346 { get; set; }
        public string Field347 { get; set; }
        public string Field348 { get; set; }
        public string Field349 { get; set; }
        public string Field350 { get; set; }
        public string Field351 { get; set; }
        public string Field352 { get; set; }
        public string Field353 { get; set; }
        public string Field354 { get; set; }
        public string Field355 { get; set; }
        public string Field356 { get; set; }
        public string Field357 { get; set; }
        public string Field358 { get; set; }
        public string Field359 { get; set; }
        public string Field360 { get; set; }
        public string Field361 { get; set; }
        public string Field362 { get; set; }
        public string Field363 { get; set; }
        public string Field364 { get; set; }
        public string Field365 { get; set; }
        public string Field366 { get; set; }
        public string Field367 { get; set; }
        public string Field368 { get; set; }
        public string Field369 { get; set; }
        public string Field370 { get; set; }
        public string Field371 { get; set; }
        public string Field372 { get; set; }
        public string Field373 { get; set; }
        public string Field374 { get; set; }
        public string Field375 { get; set; }
        public string Field376 { get; set; }
        public string Field377 { get; set; }
        public string Field378 { get; set; }
        public string Field379 { get; set; }
        public string Field380 { get; set; }
        public string Field381 { get; set; }
        public string Field382 { get; set; }
        public string Field383 { get; set; }
        public string Field384 { get; set; }
        public string Field385 { get; set; }
        public string Field386 { get; set; }
        public string Field387 { get; set; }
        public string Field388 { get; set; }
        public string Field389 { get; set; }
        public string Field390 { get; set; }
        public string Field391 { get; set; }
        public string Field392 { get; set; }
        public string Field393 { get; set; }
        public string Field394 { get; set; }
        public string Field395 { get; set; }
        public string Field396 { get; set; }
        public string Field397 { get; set; }
        public string Field398 { get; set; }
        public string Field399 { get; set; }
        public string Field400 { get; set; }
        public string Field401 { get; set; }
        public string Field402 { get; set; }
        public string Field403 { get; set; }
        public string Field404 { get; set; }
        public string Field405 { get; set; }
        public string Field406 { get; set; }
        public string Field407 { get; set; }
        public string Field408 { get; set; }
        public string Field409 { get; set; }
        public string Field410 { get; set; }
        public string Field411 { get; set; }
        public string Field412 { get; set; }
        public string Field413 { get; set; }
        public string Field414 { get; set; }
        public string Field415 { get; set; }
        public string Field416 { get; set; }
        public string Field417 { get; set; }
        public string Field418 { get; set; }
        public string Field419 { get; set; }
        public string Field420 { get; set; }
        public string Field421 { get; set; }
        public string Field422 { get; set; }
        public string Field423 { get; set; }
        public string Field424 { get; set; }
        public string Field425 { get; set; }
        public string Field426 { get; set; }
        public string Field427 { get; set; }
        public string Field428 { get; set; }
        public string Field429 { get; set; }
        public string Field430 { get; set; }
        public string Field431 { get; set; }
        public string Field432 { get; set; }
        public string Field433 { get; set; }
        public string Field434 { get; set; }
        public string Field435 { get; set; }
        public string Field436 { get; set; }
        public string Field437 { get; set; }
        public string Field438 { get; set; }
        public string Field439 { get; set; }
        public string Field440 { get; set; }
        public string Field441 { get; set; }
        public string Field442 { get; set; }
        public string Field443 { get; set; }
        public string Field444 { get; set; }
        public string Field445 { get; set; }
        public string Field446 { get; set; }
        public string Field447 { get; set; }
        public string Field448 { get; set; }
        public string Field449 { get; set; }
        public string Field450 { get; set; }
        public string Field451 { get; set; }
        public string Field452 { get; set; }
        public string Field453 { get; set; }
        public string Field454 { get; set; }
        public string Field455 { get; set; }
        public string Field456 { get; set; }
        public string Field457 { get; set; }
        public string Field458 { get; set; }
        public string Field459 { get; set; }
        public string Field460 { get; set; }
        public string Field461 { get; set; }
        public string Field462 { get; set; }
        public string Field463 { get; set; }
        public string Field464 { get; set; }
        public string Field465 { get; set; }
        public string Field466 { get; set; }
        public string Field467 { get; set; }
        public string Field468 { get; set; }
        public string Field469 { get; set; }
        public string Field470 { get; set; }
        public string Field471 { get; set; }
        public string Field472 { get; set; }
        public string Field473 { get; set; }
        public string Field474 { get; set; }
        public string Field475 { get; set; }
        public string Field476 { get; set; }
        public string Field477 { get; set; }
        public string Field478 { get; set; }
        public string Field479 { get; set; }
        public string Field480 { get; set; }
        public string Field481 { get; set; }
        public string Field482 { get; set; }
        public string Field483 { get; set; }
        public string Field484 { get; set; }
        public string Field485 { get; set; }
        public string Field486 { get; set; }
        public string Field487 { get; set; }
        public string Field488 { get; set; }
        public string Field489 { get; set; }
        public string Field490 { get; set; }
        public string Field491 { get; set; }
        public string Field492 { get; set; }
        public string Field493 { get; set; }
        public string Field494 { get; set; }
        public string Field495 { get; set; }
        public string Field496 { get; set; }
        public string Field497 { get; set; }
        public string Field498 { get; set; }
        public string Field499 { get; set; }
        public string Field500 { get; set; }
        public long FileDataID { get; set; }

    }
}
