using System;

namespace ByteWebConnector.SDK.Models.Rainmaker
{
    public class MarksmanLeadDetail
    {
        public int Id { get; set; }
        public int? ProspectId { get; set; }
        public string ProspectTrackingId { get; set; }
        public string ProspectFirstName { get; set; }
        public string ProspectMiddleName { get; set; }
        public string ProspectLastName { get; set; }
        public string ProspectSsn { get; set; }
        public string ProspectAddress1 { get; set; }
        public string ProspectAddress2 { get; set; }
        public string ProspectCity { get; set; }
        public string ProspectState { get; set; }
        public string ProspectZip { get; set; }
        public string ProspectEmail { get; set; }
        public string ProspectHomePhone { get; set; }
        public string ProspectMobilePhone { get; set; }
        public string ProspectWorkPhone { get; set; }
        public DateTime? ProspectDob { get; set; }
        public string ProspectCustomerId { get; set; }
        public int? ProspectSource { get; set; }
        public int? ProspectStatus { get; set; }
        public int? ProspectLoanAmount { get; set; }
        public int? ProspectPurchasePrice { get; set; }
        public int? ProspectDownPayment { get; set; }
        public int? ProspectLockInPeriod { get; set; }
        public int? ProspectLoanPurpose { get; set; }
        public decimal? ProspectLtv { get; set; }
        public int? ProspectOccupancy { get; set; }
        public int? ProspectFico { get; set; }
        public string ProspectPropertyAddress1 { get; set; }
        public string ProspectPropertyAddress2 { get; set; }
        public string ProspectPropertyCity { get; set; }
        public string ProspectPropertyState { get; set; }
        public string ProspectPropertyZip { get; set; }
        public string ProspectPropertyCounty { get; set; }
        public int? ProspectLoanOfficerId { get; set; }
        public string ProspectLoanOfficerName { get; set; }
        public string ProspectLoanOfficerEmail { get; set; }
        public string ProspectLoanOfficerUsername { get; set; }
        public string ProspectLoanOfficerPhone { get; set; }
        public string ProspectRealtorName { get; set; }
        public string ProspectRealtorPhone { get; set; }
        public string ProspectRealtorEmail { get; set; }
        public string ProspectProjectedCloseDate { get; set; }
        public int? ProspectFoundAHome { get; set; }
        public string ProspectSellersName { get; set; }
        public string ProspectSellersEmail { get; set; }
        public string ProspectOriginalAssignedLo { get; set; }
        public string ProspectLastAssignedDate { get; set; }
        public string ProspectCbFico { get; set; }
        public string CurrentMortgageBalance { get; set; }
        public string CurrentMortgageRate { get; set; }
        public string CurrentMortgagePayment { get; set; }
        public string AgencyCaseNum { get; set; }
        public string LenderCaseNum { get; set; }
        public string LegalDescription { get; set; }
        public string YearLotAcquired { get; set; }
        public string OriginalCost { get; set; }
        public string AmountLien { get; set; }
        public string PresentValue { get; set; }
        public string PurposeRefi { get; set; }
        public string MannerTitleHeld { get; set; }
        public string PropertyImprovements { get; set; }
        public string ImprovementMade { get; set; }
        public string CostOfImprovements { get; set; }
        public string ProspectDependents { get; set; }
        public string ProspectDependentsAge { get; set; }
        public string ProspectYearsInSchool { get; set; }
        public string ProspectMaritalStatus { get; set; }
        public string ProspectSex { get; set; }
        public string ProspectRace { get; set; }
        public string ProspectEthnicity { get; set; }
        public string ProspectCbDependents { get; set; }
        public string ProspectCbDependentsAge { get; set; }
        public string ProspectCbYearsInSchool { get; set; }
        public string ProspectCbMaritalStatus { get; set; }
        public string ProspectCbSex { get; set; }
        public string ProspectCbRace { get; set; }
        public string ProspectCbEthnicity { get; set; }
        public string ProspectEstateHeld { get; set; }
        public string ProspectExpirationDate { get; set; }
        public string ProspectDownPaymentType { get; set; }
        public int? ProspectProduct1VendorId { get; set; }
        public int? ProspectProduct1Id { get; set; }
        public decimal? ProspectProduct1Rate { get; set; }
        public decimal? ProspectProduct1Price { get; set; }
        public decimal? ProspectProduct1Apr { get; set; }
        public string ProspectProduct1LtProductName { get; set; }
        public int? ProspectProduct1MonthlyPayment { get; set; }
        public int? ProspectProduct2VendorId { get; set; }
        public int? ProspectProduct2Id { get; set; }
        public decimal? ProspectProduct2Rate { get; set; }
        public decimal? ProspectProduct2Price { get; set; }
        public decimal? ProspectProduct2Apr { get; set; }
        public string ProspectProduct2LtProductName { get; set; }
        public int? ProspectProduct2MonthlyPayment { get; set; }
        public int? ProspectProduct3VendorId { get; set; }
        public int? ProspectProduct3Id { get; set; }
        public decimal? ProspectProduct3Rate { get; set; }
        public decimal? ProspectProduct3Price { get; set; }
        public decimal? ProspectProduct3Apr { get; set; }
        public string ProspectProduct3LtProductName { get; set; }
        public int? ProspectProduct3MonthlyPayment { get; set; }
        public int? ProspectCurrResOwnOrRent { get; set; }
        public int? ProspectCurrResNumberOfYears { get; set; }
        public int? ProspectCurrResNumberOfMonths { get; set; }
        public string ProspectCurrResAddress1 { get; set; }
        public string ProspectCurrResAddress2 { get; set; }
        public string ProspectCurrResCity { get; set; }
        public string ProspectCurrResState { get; set; }
        public string ProspectCurrResZip { get; set; }
        public int? ProspectPrevResOwnOrRent { get; set; }
        public int? ProspectPrevResNumberOfYears { get; set; }
        public int? ProspectPrevResNumberOfMonths { get; set; }
        public string ProspectPrevResAddress1 { get; set; }
        public string ProspectPrevResAddress2 { get; set; }
        public string ProspectPrevResCity { get; set; }
        public string ProspectPrevResState { get; set; }
        public string ProspectPrevResZip { get; set; }
        public string ProspectCurrEmpEmployerName { get; set; }
        public int? ProspectCurrEmpMonthsOnJob { get; set; }
        public int? ProspectCurrEmpYearsOnJob { get; set; }
        public int? ProspectCurrEmpYearsOfExperience { get; set; }
        public string ProspectCurrEmpTitle { get; set; }
        public string ProspectCurrEmpPhone { get; set; }
        public string ProspectCurrEmpPhoneExtension { get; set; }
        public int? ProspectCurrEmpIsSelfEmployed { get; set; }
        public string ProspectCurrEmpAddress1 { get; set; }
        public string ProspectCurrEmpAddress2 { get; set; }
        public string ProspectCurrEmpCity { get; set; }
        public string ProspectCurrEmpState { get; set; }
        public string ProspectCurrEmpZip { get; set; }
        public DateTime? ProspectCurrEmpStartDate { get; set; }
        public DateTime? ProspectCurrEmpEndDate { get; set; }
        public string ProspectPrevEmpEmployerName { get; set; }
        public int? ProspectPrevEmpMonthsOnJob { get; set; }
        public int? ProspectPrevEmpYearsOnJob { get; set; }
        public int? ProspectPrevEmpYearsOfExperience { get; set; }
        public string ProspectPrevEmpTitle { get; set; }
        public string ProspectPrevEmpPhone { get; set; }
        public string ProspectPrevEmpPhoneExtension { get; set; }
        public int? ProspectPrevEmpIsSelfEmployed { get; set; }
        public string ProspectPrevEmpAddress1 { get; set; }
        public string ProspectPrevEmpAddress2 { get; set; }
        public string ProspectPrevEmpCity { get; set; }
        public string ProspectPrevEmpState { get; set; }
        public string ProspectPrevEmpZip { get; set; }
        public DateTime? ProspectPrevEmpStartDate { get; set; }
        public DateTime? ProspectPrevEmpEndDate { get; set; }
        public int? ProspectCondo { get; set; }
        public int? ProspectUnits { get; set; }
        public int? ProspectWaiveEscrow { get; set; }
        public int? ProspectSecondaryFinancing { get; set; }
        public int? ProspectManufacturedHome { get; set; }
        public string ProspectAddDate { get; set; }
        public string ProspectCreditRating { get; set; }
        public string ProspectBankruptcy { get; set; }
        public int? ProspectMonthlyIncome { get; set; }
        public int? ProspectMonthlyDebt { get; set; }
        public string ProspectOccupationalStatus { get; set; }
        public string ProspectFilters { get; set; }
        public string ProspectPropertyYearBuilt { get; set; }
        public int? ProspectContactPreference { get; set; }
        public int? ProspectFirstTimeHomeBuyer { get; set; }
        public int? ProspectIncomeType { get; set; }
        public int? ProspectIncomeVerify { get; set; }
        public int? ProspectChapter7Years { get; set; }
        public int? ProspectChapter13Years { get; set; }
        public int? ProspectForeclosureYears { get; set; }
        public int? ProspectLate30 { get; set; }
        public int? ProspectLate60 { get; set; }
        public int? ProspectLate90 { get; set; }
        public int? ProspectLate120 { get; set; }
        public int? ProspectGrossDisposableIncome { get; set; }
        public int? ProspectDeclarationBaseIncome { get; set; }
        public int? ProspectDeclarationBonuses { get; set; }
        public int? ProspectDeclarationNetRentalIncome { get; set; }
        public int? ProspectDeclarationOvertime { get; set; }
        public int? ProspectDeclarationCommissions { get; set; }
        public int? ProspectDeclarationInstallmentDebts { get; set; }
        public int? ProspectDeclarationContinuingDebts { get; set; }
        public int? ProspectDeclaration1 { get; set; }
        public int? ProspectDeclaration2 { get; set; }
        public int? ProspectDeclaration3 { get; set; }
        public int? ProspectDeclaration4 { get; set; }
        public int? ProspectDeclaration5 { get; set; }
        public int? ProspectDeclaration6 { get; set; }
        public int? ProspectDeclaration7 { get; set; }
        public int? ProspectDeclaration8 { get; set; }
        public int? ProspectDeclaration9 { get; set; }
        public int? ProspectDeclaration10 { get; set; }
        public int? ProspectDeclaration11 { get; set; }
        public string ProspectCbFirstName { get; set; }
        public string ProspectCbMiddleName { get; set; }
        public string ProspectCbLastName { get; set; }
        public string ProspectCbEmail { get; set; }
        public string ProspectCbHomePhone { get; set; }
        public string ProspectCbMobilePhone { get; set; }
        public string ProspectCbWorkPhone { get; set; }
        public string ProspectCbSsn { get; set; }
        public DateTime? ProspectCbDob { get; set; }
        public int? ProspectCbCurrResOwnOrRent { get; set; }
        public int? ProspectCbCurrResNumberOfYears { get; set; }
        public int? ProspectCbCurrResNumberOfMonths { get; set; }
        public string ProspectCbCurrResAddress1 { get; set; }
        public string ProspectCbCurrResAddress2 { get; set; }
        public string ProspectCbCurrResCity { get; set; }
        public string ProspectCbCurrResState { get; set; }
        public string ProspectCbCurrResZip { get; set; }
        public int? ProspectCbPrevResOwnOrRent { get; set; }
        public int? ProspectCbPrevResNumberOfYears { get; set; }
        public int? ProspectCbPrevResNumberOfMonths { get; set; }
        public string ProspectCbPrevResAddress1 { get; set; }
        public string ProspectCbPrevResAddress2 { get; set; }
        public string ProspectCbPrevResCity { get; set; }
        public string ProspectCbPrevResState { get; set; }
        public string ProspectCbPrevResZip { get; set; }
        public string ProspectCbCurrEmpEmployerName { get; set; }
        public int? ProspectCbCurrEmpMonthsOnJob { get; set; }
        public int? ProspectCbCurrEmpYearsOnJob { get; set; }
        public int? ProspectCbCurrEmpYearsOfExperience { get; set; }
        public string ProspectCbCurrEmpTitle { get; set; }
        public string ProspectCbCurrEmpPhone { get; set; }
        public string ProspectCbCurrEmpPhoneExtension { get; set; }
        public int? ProspectCbCurrEmpIsSelfEmployed { get; set; }
        public string ProspectCbCurrEmpAddress1 { get; set; }
        public string ProspectCbCurrEmpAddress2 { get; set; }
        public string ProspectCbCurrEmpCity { get; set; }
        public string ProspectCbCurrEmpState { get; set; }
        public string ProspectCbCurrEmpZip { get; set; }
        public DateTime? ProspectCbCurrEmpStartDate { get; set; }
        public DateTime? ProspectCbCurrEmpEndDate { get; set; }
        public string ProspectCbPrevEmpEmployerName { get; set; }
        public int? ProspectCbPrevEmpMonthsOnJob { get; set; }
        public int? ProspectCbPrevEmpYearsOnJob { get; set; }
        public int? ProspectCbPrevEmpYearsOfExperience { get; set; }
        public string ProspectCbPrevEmpTitle { get; set; }
        public string ProspectCbPrevEmpPhone { get; set; }
        public string ProspectCbPrevEmpPhoneExtension { get; set; }
        public int? ProspectCbPrevEmpIsSelfEmployed { get; set; }
        public string ProspectCbPrevEmpAddress1 { get; set; }
        public string ProspectCbPrevEmpAddress2 { get; set; }
        public string ProspectCbPrevEmpCity { get; set; }
        public string ProspectCbPrevEmpState { get; set; }
        public string ProspectCbPrevEmpZip { get; set; }
        public DateTime? ProspectCbPrevEmpStartDate { get; set; }
        public DateTime? ProspectCbPrevEmpEndDate { get; set; }
        public int? ProspectCbDeclarationBaseIncome { get; set; }
        public int? ProspectCbDeclarationBonuses { get; set; }
        public int? ProspectCbDeclarationNetRentalIncome { get; set; }
        public int? ProspectCbDeclarationOvertime { get; set; }
        public int? ProspectCbDeclarationCommissions { get; set; }
        public int? ProspectCbDeclarationInstallmentDebts { get; set; }
        public int? ProspectCbDeclarationContinuingDebts { get; set; }
        public int? ProspectCbDeclaration1 { get; set; }
        public int? ProspectCbDeclaration2 { get; set; }
        public int? ProspectCbDeclaration3 { get; set; }
        public int? ProspectCbDeclaration4 { get; set; }
        public int? ProspectCbDeclaration5 { get; set; }
        public int? ProspectCbDeclaration6 { get; set; }
        public int? ProspectCbDeclaration7 { get; set; }
        public int? ProspectCbDeclaration8 { get; set; }
        public int? ProspectCbDeclaration9 { get; set; }
        public int? ProspectCbDeclaration10 { get; set; }
        public int? ProspectCbDeclaration11 { get; set; }
        public string ProspectSourceName { get; set; }
        public string ProspectCfName1 { get; set; }
        public string ProspectCfValue1 { get; set; }
        public string ProspectCfName2 { get; set; }
        public string ProspectCfValue2 { get; set; }
        public string ProspectCfName3 { get; set; }
        public string ProspectCfValue3 { get; set; }
        public string ProspectCfName4 { get; set; }
        public string ProspectCfValue4 { get; set; }
        public string ProspectCfName5 { get; set; }
        public string ProspectCfValue5 { get; set; }
        public string ProspectCfName6 { get; set; }
        public string ProspectCfValue6 { get; set; }
        public string ProspectCfName7 { get; set; }
        public string ProspectCfValue7 { get; set; }
        public string ProspectCfName8 { get; set; }
        public string ProspectCfValue8 { get; set; }
        public string ProspectCfName9 { get; set; }
        public string ProspectCfValue9 { get; set; }
        public string ProspectCfName10 { get; set; }
        public string ProspectCfValue10 { get; set; }
        public string BranchName { get; set; }
        public string ProspectNotes { get; set; }
        public string CallDisposition { get; set; }

        public MarksmanLead MarksmanLead { get; set; }
    }
}